builders:
  app_metadata:
    import: "package:app_metadata/src/app_metadata_generator.dart"
    builder_factories: ["appMetadataBuilder"]
    build_extensions: {".dart": ["app_metadata.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
