// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Resolves a `(value, column_index)` pair to every category whose range
/// contains `value` at the same `column_index`. More than one row can
/// match (e.g. a plus/minus pair), in which case every match is kept,
/// deduplicated and in first-seen order.
List<CategoryMatch> resolveCategories({
  required List<RangeCategory> categories,
  required int value,
  required int columnIndex,
}) => RustLib.instance.api.crateRangeCategoryResolveCategories(
  categories: categories,
  value: value,
  columnIndex: columnIndex,
);

/// A category a `(value, column_index)` pair resolved to.
class CategoryMatch {
  final String categoryKey;
  final String? tag;
  final int rangeStart;
  final int rangeEnd;

  const CategoryMatch({
    required this.categoryKey,
    this.tag,
    required this.rangeStart,
    required this.rangeEnd,
  });

  @override
  int get hashCode =>
      categoryKey.hashCode ^
      tag.hashCode ^
      rangeStart.hashCode ^
      rangeEnd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryMatch &&
          runtimeType == other.runtimeType &&
          categoryKey == other.categoryKey &&
          tag == other.tag &&
          rangeStart == other.rangeStart &&
          rangeEnd == other.rangeEnd;
}

/// One row of a value-range-to-category mapping table.
class RangeCategory {
  final String id;
  final int rangeStart;
  final int rangeEnd;
  final int columnIndex;
  final String categoryKey;
  final String? tag;

  const RangeCategory({
    required this.id,
    required this.rangeStart,
    required this.rangeEnd,
    required this.columnIndex,
    required this.categoryKey,
    this.tag,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rangeStart.hashCode ^
      rangeEnd.hashCode ^
      columnIndex.hashCode ^
      categoryKey.hashCode ^
      tag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RangeCategory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rangeStart == other.rangeStart &&
          rangeEnd == other.rangeEnd &&
          columnIndex == other.columnIndex &&
          categoryKey == other.categoryKey &&
          tag == other.tag;
}
