import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../i18n/gen/strings.g.dart';

/// Every locale the app is translated into, as generated by `slang` from
/// the `lib/i18n/*.i18n.json` files. Display names are looked up per
/// locale via `t.languages[locale.languageCode]`.
final availableLocalesProvider = Provider<List<AppLocale>>((ref) {
  return AppLocale.values;
});
