// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1391955981;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__category_grid__build_category_grid_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "build_category_grid",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::category_grid::CategoryGridRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Ok::<_, ()>(crate::category_grid::build_category_grid(api_request))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__resistance__calculate_attribute_resistance_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calculate_attribute_resistance",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_selection =
                <crate::resistance::BodyColorSelection>::sse_decode(&mut deserializer);
            let api_master_data =
                <crate::resistance::ResistanceMasterData>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::resistance::calculate_attribute_resistance(
                    &api_selection,
                    &api_master_data,
                )?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__resistance__calculate_color_abnormality_resistance_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calculate_color_abnormality_resistance",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_selection =
                <crate::resistance::BodyColorSelection>::sse_decode(&mut deserializer);
            let api_master_data =
                <crate::resistance::ResistanceMasterData>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Ok::<_, ()>(crate::resistance::calculate_color_abnormality_resistance(
                        &api_selection,
                        &api_master_data,
                    ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__resistance__calculate_correction_stat_bonus_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calculate_correction_stat_bonus",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_input =
                <crate::resistance::ResistanceCorrectionInput>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::resistance::calculate_correction_stat_bonus(
                    &api_input,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__resistance__calculate_denpa_men_resistances_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calculate_denpa_men_resistances",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_selection =
                <crate::resistance::BodyColorSelection>::sse_decode(&mut deserializer);
            let api_head_shape =
                <crate::resistance::HeadShapeResistanceBonuses>::sse_decode(&mut deserializer);
            let api_master_data =
                <crate::resistance::ResistanceMasterData>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::resistance::calculate_denpa_men_resistances(
                    &api_selection,
                    &api_head_shape,
                    &api_master_data,
                )?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__table_row__collect_columns_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "collect_columns",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_rows = <Vec<crate::table_row::TableRow>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::table_row::collect_columns(&api_rows))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__category_grid__compact_categories_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "compact_categories",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_categories =
                <Vec<crate::range_category::RangeCategory>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Ok::<_, ()>(crate::category_grid::compact_categories(&api_categories))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__resistance__find_color_combination_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "find_color_combination",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_target =
                <Vec<crate::resistance::AttributeResistance>>::sse_decode(&mut deserializer);
            let api_master_data =
                <crate::resistance::ResistanceMasterData>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok =
                    crate::resistance::find_color_combination(&api_target, &api_master_data)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__status_match__find_matching_columns_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "find_matching_columns",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_primary = <crate::status_match::StatusCriterion>::sse_decode(&mut deserializer);
            let api_others =
                <Vec<crate::status_match::StatusCriterion>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::status_match::find_matching_columns(
                    &api_primary,
                    &api_others,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__range_category__resolve_categories_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "resolve_categories",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_categories =
                <Vec<crate::range_category::RangeCategory>>::sse_decode(&mut deserializer);
            let api_value = <i32>::sse_decode(&mut deserializer);
            let api_column_index = <i32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::range_category::resolve_categories(
                    &api_categories,
                    api_value,
                    api_column_index,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::resistance::AbnormalityResistance {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_abnormalityId = <String>::sse_decode(deserializer);
        let mut var_value = <i32>::sse_decode(deserializer);
        return crate::resistance::AbnormalityResistance {
            abnormality_id: var_abnormalityId,
            value: var_value,
        };
    }
}

impl SseDecode for crate::resistance::AttributeResistance {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_attributeId = <String>::sse_decode(deserializer);
        let mut var_value = <i32>::sse_decode(deserializer);
        return crate::resistance::AttributeResistance {
            attribute_id: var_attributeId,
            value: var_value,
        };
    }
}

impl SseDecode for crate::resistance::AttributeResistanceBonus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_attributeId = <String>::sse_decode(deserializer);
        let mut var_bonus = <i32>::sse_decode(deserializer);
        return crate::resistance::AttributeResistanceBonus {
            attribute_id: var_attributeId,
            bonus: var_bonus,
        };
    }
}

impl SseDecode for crate::resistance::BodyColorAbnormalityResistanceRule {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_colorId = <String>::sse_decode(deserializer);
        let mut var_abnormalityResistanceBonuses =
            <Vec<crate::resistance::ResistanceBonus>>::sse_decode(deserializer);
        return crate::resistance::BodyColorAbnormalityResistanceRule {
            color_id: var_colorId,
            abnormality_resistance_bonuses: var_abnormalityResistanceBonuses,
        };
    }
}

impl SseDecode for crate::resistance::BodyColorResistanceRule {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_colorId = <String>::sse_decode(deserializer);
        let mut var_attributeResistanceBonuses =
            <Vec<crate::resistance::AttributeResistanceBonus>>::sse_decode(deserializer);
        return crate::resistance::BodyColorResistanceRule {
            color_id: var_colorId,
            attribute_resistance_bonuses: var_attributeResistanceBonuses,
        };
    }
}

impl SseDecode for crate::resistance::BodyColorSelection {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_bodyColors = <Vec<String>>::sse_decode(deserializer);
        let mut var_isSpColor = <bool>::sse_decode(deserializer);
        return crate::resistance::BodyColorSelection {
            body_colors: var_bodyColors,
            is_sp_color: var_isSpColor,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::category_grid::CategoryCell {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_categoryId = <String>::sse_decode(deserializer);
        let mut var_rangeStart = <i32>::sse_decode(deserializer);
        let mut var_rangeEnd = <i32>::sse_decode(deserializer);
        let mut var_columnIndex = <i32>::sse_decode(deserializer);
        let mut var_categoryKey = <String>::sse_decode(deserializer);
        let mut var_tag = <Option<String>>::sse_decode(deserializer);
        let mut var_liveValues = <Vec<i32>>::sse_decode(deserializer);
        let mut var_isMatch = <bool>::sse_decode(deserializer);
        return crate::category_grid::CategoryCell {
            category_id: var_categoryId,
            range_start: var_rangeStart,
            range_end: var_rangeEnd,
            column_index: var_columnIndex,
            category_key: var_categoryKey,
            tag: var_tag,
            live_values: var_liveValues,
            is_match: var_isMatch,
        };
    }
}

impl SseDecode for crate::category_grid::CategoryGrid {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_categoryCells =
            <Vec<crate::category_grid::CategoryCell>>::sse_decode(deserializer);
        let mut var_valueCells = <Vec<crate::category_grid::ValueCell>>::sse_decode(deserializer);
        return crate::category_grid::CategoryGrid {
            category_cells: var_categoryCells,
            value_cells: var_valueCells,
        };
    }
}

impl SseDecode for crate::category_grid::CategoryGridRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_categories =
            <Vec<crate::range_category::RangeCategory>>::sse_decode(deserializer);
        let mut var_primaryRows = <Vec<crate::table_row::TableRow>>::sse_decode(deserializer);
        let mut var_companionRows = <Vec<crate::table_row::TableRow>>::sse_decode(deserializer);
        let mut var_matchColumnIndex = <i32>::sse_decode(deserializer);
        let mut var_matchLineOffset = <i32>::sse_decode(deserializer);
        let mut var_matchValue = <i32>::sse_decode(deserializer);
        return crate::category_grid::CategoryGridRequest {
            categories: var_categories,
            primary_rows: var_primaryRows,
            companion_rows: var_companionRows,
            match_column_index: var_matchColumnIndex,
            match_line_offset: var_matchLineOffset,
            match_value: var_matchValue,
        };
    }
}

impl SseDecode for crate::range_category::CategoryMatch {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_categoryKey = <String>::sse_decode(deserializer);
        let mut var_tag = <Option<String>>::sse_decode(deserializer);
        let mut var_rangeStart = <i32>::sse_decode(deserializer);
        let mut var_rangeEnd = <i32>::sse_decode(deserializer);
        return crate::range_category::CategoryMatch {
            category_key: var_categoryKey,
            tag: var_tag,
            range_start: var_rangeStart,
            range_end: var_rangeEnd,
        };
    }
}

impl SseDecode for crate::table_row::ColumnEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_value = <i32>::sse_decode(deserializer);
        let mut var_lineOffset = <i32>::sse_decode(deserializer);
        return crate::table_row::ColumnEntry {
            value: var_value,
            line_offset: var_lineOffset,
        };
    }
}

impl SseDecode for crate::resistance::CorrectionBonuses {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_statBonus = <crate::resistance::StatBonus>::sse_decode(deserializer);
        let mut var_abnormalityResistanceBonuses =
            <Vec<crate::resistance::ResistanceBonus>>::sse_decode(deserializer);
        let mut var_attributeResistanceBonuses =
            <Vec<crate::resistance::AttributeResistanceBonus>>::sse_decode(deserializer);
        return crate::resistance::CorrectionBonuses {
            stat_bonus: var_statBonus,
            abnormality_resistance_bonuses: var_abnormalityResistanceBonuses,
            attribute_resistance_bonuses: var_attributeResistanceBonuses,
        };
    }
}

impl SseDecode for crate::resistance::DenpaMenResistances {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_abnormalityResistances =
            <Vec<crate::resistance::AbnormalityResistance>>::sse_decode(deserializer);
        let mut var_attributeResistance =
            <Vec<crate::resistance::AttributeResistance>>::sse_decode(deserializer);
        return crate::resistance::DenpaMenResistances {
            abnormality_resistances: var_abnormalityResistances,
            attribute_resistance: var_attributeResistance,
        };
    }
}

impl SseDecode for crate::resistance::HeadShapeResistanceBonuses {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_abnormalityResistanceBonuses =
            <Vec<crate::resistance::ResistanceBonus>>::sse_decode(deserializer);
        let mut var_attributeResistanceBonuses =
            <Vec<crate::resistance::AttributeResistanceBonus>>::sse_decode(deserializer);
        return crate::resistance::HeadShapeResistanceBonuses {
            abnormality_resistance_bonuses: var_abnormalityResistanceBonuses,
            attribute_resistance_bonuses: var_attributeResistanceBonuses,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::resistance::AbnormalityResistance> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::resistance::AbnormalityResistance>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::resistance::AttributeResistance> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::resistance::AttributeResistance>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::resistance::AttributeResistanceBonus> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::resistance::AttributeResistanceBonus>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::resistance::BodyColorAbnormalityResistanceRule> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(
                <crate::resistance::BodyColorAbnormalityResistanceRule>::sse_decode(deserializer),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::resistance::BodyColorResistanceRule> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::resistance::BodyColorResistanceRule>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::category_grid::CategoryCell> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::category_grid::CategoryCell>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::range_category::CategoryMatch> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::range_category::CategoryMatch>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::table_row::ColumnEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::table_row::ColumnEntry>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::resistance::CorrectionBonuses> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::resistance::CorrectionBonuses>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<Vec<crate::table_row::ColumnEntry>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<Vec<crate::table_row::ColumnEntry>>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<Option<i32>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<Option<i32>>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<i32>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::range_category::RangeCategory> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::range_category::RangeCategory>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::resistance::ResistanceAttribute> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::resistance::ResistanceAttribute>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::resistance::ResistanceBonus> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::resistance::ResistanceBonus>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::status_match::StatusCriterion> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::status_match::StatusCriterion>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::status_match::StatusMatch> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::status_match::StatusMatch>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::table_row::TableRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::table_row::TableRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::category_grid::ValueCell> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::category_grid::ValueCell>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::resistance::BodyColorSelection> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::resistance::BodyColorSelection>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::range_category::RangeCategory {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_rangeStart = <i32>::sse_decode(deserializer);
        let mut var_rangeEnd = <i32>::sse_decode(deserializer);
        let mut var_columnIndex = <i32>::sse_decode(deserializer);
        let mut var_categoryKey = <String>::sse_decode(deserializer);
        let mut var_tag = <Option<String>>::sse_decode(deserializer);
        return crate::range_category::RangeCategory {
            id: var_id,
            range_start: var_rangeStart,
            range_end: var_rangeEnd,
            column_index: var_columnIndex,
            category_key: var_categoryKey,
            tag: var_tag,
        };
    }
}

impl SseDecode for crate::resistance::ResistanceAttribute {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_index = <i32>::sse_decode(deserializer);
        let mut var_isElemental = <bool>::sse_decode(deserializer);
        return crate::resistance::ResistanceAttribute {
            id: var_id,
            index: var_index,
            is_elemental: var_isElemental,
        };
    }
}

impl SseDecode for crate::resistance::ResistanceBonus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_bonus = <i32>::sse_decode(deserializer);
        return crate::resistance::ResistanceBonus {
            id: var_id,
            bonus: var_bonus,
        };
    }
}

impl SseDecode for crate::resistance::ResistanceCorrectionInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_corrections =
            <Vec<crate::resistance::CorrectionBonuses>>::sse_decode(deserializer);
        let mut var_additionalCorrection =
            <crate::resistance::CorrectionBonuses>::sse_decode(deserializer);
        return crate::resistance::ResistanceCorrectionInput {
            corrections: var_corrections,
            additional_correction: var_additionalCorrection,
        };
    }
}

impl SseDecode for crate::resistance::ResistanceMasterData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_attributes =
            <Vec<crate::resistance::ResistanceAttribute>>::sse_decode(deserializer);
        let mut var_bodyColorResistanceRules =
            <Vec<crate::resistance::BodyColorResistanceRule>>::sse_decode(deserializer);
        let mut var_bodyColorAbnormalityResistanceRules =
            <Vec<crate::resistance::BodyColorAbnormalityResistanceRule>>::sse_decode(deserializer);
        return crate::resistance::ResistanceMasterData {
            attributes: var_attributes,
            body_color_resistance_rules: var_bodyColorResistanceRules,
            body_color_abnormality_resistance_rules: var_bodyColorAbnormalityResistanceRules,
        };
    }
}

impl SseDecode for crate::resistance::StatBonus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_hp = <i32>::sse_decode(deserializer);
        let mut var_ap = <i32>::sse_decode(deserializer);
        let mut var_attack = <i32>::sse_decode(deserializer);
        let mut var_defense = <i32>::sse_decode(deserializer);
        let mut var_speed = <i32>::sse_decode(deserializer);
        let mut var_evasionRate = <i32>::sse_decode(deserializer);
        return crate::resistance::StatBonus {
            hp: var_hp,
            ap: var_ap,
            attack: var_attack,
            defense: var_defense,
            speed: var_speed,
            evasion_rate: var_evasionRate,
        };
    }
}

impl SseDecode for crate::status_match::StatusCriterion {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_rows = <Vec<crate::table_row::TableRow>>::sse_decode(deserializer);
        let mut var_targetValue = <i32>::sse_decode(deserializer);
        return crate::status_match::StatusCriterion {
            rows: var_rows,
            target_value: var_targetValue,
        };
    }
}

impl SseDecode for crate::status_match::StatusMatch {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_group = <Vec<String>>::sse_decode(deserializer);
        let mut var_lineOffset = <i32>::sse_decode(deserializer);
        let mut var_columnIndex = <i32>::sse_decode(deserializer);
        return crate::status_match::StatusMatch {
            group: var_group,
            line_offset: var_lineOffset,
            column_index: var_columnIndex,
        };
    }
}

impl SseDecode for crate::table_row::TableRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_group = <Vec<String>>::sse_decode(deserializer);
        let mut var_lineOffset = <i32>::sse_decode(deserializer);
        let mut var_values = <Vec<Option<i32>>>::sse_decode(deserializer);
        return crate::table_row::TableRow {
            group: var_group,
            line_offset: var_lineOffset,
            values: var_values,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::category_grid::ValueCell {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_columnIndex = <i32>::sse_decode(deserializer);
        let mut var_lineOffset = <i32>::sse_decode(deserializer);
        let mut var_value = <i32>::sse_decode(deserializer);
        let mut var_isMatch = <bool>::sse_decode(deserializer);
        return crate::category_grid::ValueCell {
            column_index: var_columnIndex,
            line_offset: var_lineOffset,
            value: var_value,
            is_match: var_isMatch,
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__category_grid__build_category_grid_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__resistance__calculate_attribute_resistance_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => wire__crate__resistance__calculate_color_abnormality_resistance_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        4 => wire__crate__resistance__calculate_correction_stat_bonus_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__resistance__calculate_denpa_men_resistances_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        6 => wire__crate__table_row__collect_columns_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__category_grid__compact_categories_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__resistance__find_color_combination_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__status_match__find_matching_columns_impl(ptr, rust_vec_len, data_len),
        10 => wire__crate__range_category__resolve_categories_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::AbnormalityResistance {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.abnormality_id.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::AbnormalityResistance
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::AbnormalityResistance>
    for crate::resistance::AbnormalityResistance
{
    fn into_into_dart(self) -> crate::resistance::AbnormalityResistance {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::AttributeResistance {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.attribute_id.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::AttributeResistance
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::AttributeResistance>
    for crate::resistance::AttributeResistance
{
    fn into_into_dart(self) -> crate::resistance::AttributeResistance {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::AttributeResistanceBonus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.attribute_id.into_into_dart().into_dart(),
            self.bonus.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::AttributeResistanceBonus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::AttributeResistanceBonus>
    for crate::resistance::AttributeResistanceBonus
{
    fn into_into_dart(self) -> crate::resistance::AttributeResistanceBonus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::BodyColorAbnormalityResistanceRule {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.color_id.into_into_dart().into_dart(),
            self.abnormality_resistance_bonuses
                .into_into_dart()
                .into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::BodyColorAbnormalityResistanceRule
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::BodyColorAbnormalityResistanceRule>
    for crate::resistance::BodyColorAbnormalityResistanceRule
{
    fn into_into_dart(self) -> crate::resistance::BodyColorAbnormalityResistanceRule {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::BodyColorResistanceRule {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.color_id.into_into_dart().into_dart(),
            self.attribute_resistance_bonuses
                .into_into_dart()
                .into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::BodyColorResistanceRule
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::BodyColorResistanceRule>
    for crate::resistance::BodyColorResistanceRule
{
    fn into_into_dart(self) -> crate::resistance::BodyColorResistanceRule {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::BodyColorSelection {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.body_colors.into_into_dart().into_dart(),
            self.is_sp_color.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::BodyColorSelection
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::BodyColorSelection>
    for crate::resistance::BodyColorSelection
{
    fn into_into_dart(self) -> crate::resistance::BodyColorSelection {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::category_grid::CategoryCell {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.category_id.into_into_dart().into_dart(),
            self.range_start.into_into_dart().into_dart(),
            self.range_end.into_into_dart().into_dart(),
            self.column_index.into_into_dart().into_dart(),
            self.category_key.into_into_dart().into_dart(),
            self.tag.into_into_dart().into_dart(),
            self.live_values.into_into_dart().into_dart(),
            self.is_match.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::category_grid::CategoryCell
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::category_grid::CategoryCell>
    for crate::category_grid::CategoryCell
{
    fn into_into_dart(self) -> crate::category_grid::CategoryCell {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::category_grid::CategoryGrid {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.category_cells.into_into_dart().into_dart(),
            self.value_cells.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::category_grid::CategoryGrid
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::category_grid::CategoryGrid>
    for crate::category_grid::CategoryGrid
{
    fn into_into_dart(self) -> crate::category_grid::CategoryGrid {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::category_grid::CategoryGridRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.categories.into_into_dart().into_dart(),
            self.primary_rows.into_into_dart().into_dart(),
            self.companion_rows.into_into_dart().into_dart(),
            self.match_column_index.into_into_dart().into_dart(),
            self.match_line_offset.into_into_dart().into_dart(),
            self.match_value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::category_grid::CategoryGridRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::category_grid::CategoryGridRequest>
    for crate::category_grid::CategoryGridRequest
{
    fn into_into_dart(self) -> crate::category_grid::CategoryGridRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::range_category::CategoryMatch {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.category_key.into_into_dart().into_dart(),
            self.tag.into_into_dart().into_dart(),
            self.range_start.into_into_dart().into_dart(),
            self.range_end.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::range_category::CategoryMatch
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::range_category::CategoryMatch>
    for crate::range_category::CategoryMatch
{
    fn into_into_dart(self) -> crate::range_category::CategoryMatch {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::table_row::ColumnEntry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.value.into_into_dart().into_dart(),
            self.line_offset.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::table_row::ColumnEntry {}
impl flutter_rust_bridge::IntoIntoDart<crate::table_row::ColumnEntry>
    for crate::table_row::ColumnEntry
{
    fn into_into_dart(self) -> crate::table_row::ColumnEntry {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::CorrectionBonuses {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.stat_bonus.into_into_dart().into_dart(),
            self.abnormality_resistance_bonuses
                .into_into_dart()
                .into_dart(),
            self.attribute_resistance_bonuses
                .into_into_dart()
                .into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::CorrectionBonuses
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::CorrectionBonuses>
    for crate::resistance::CorrectionBonuses
{
    fn into_into_dart(self) -> crate::resistance::CorrectionBonuses {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::DenpaMenResistances {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.abnormality_resistances.into_into_dart().into_dart(),
            self.attribute_resistance.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::DenpaMenResistances
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::DenpaMenResistances>
    for crate::resistance::DenpaMenResistances
{
    fn into_into_dart(self) -> crate::resistance::DenpaMenResistances {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::HeadShapeResistanceBonuses {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.abnormality_resistance_bonuses
                .into_into_dart()
                .into_dart(),
            self.attribute_resistance_bonuses
                .into_into_dart()
                .into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::HeadShapeResistanceBonuses
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::HeadShapeResistanceBonuses>
    for crate::resistance::HeadShapeResistanceBonuses
{
    fn into_into_dart(self) -> crate::resistance::HeadShapeResistanceBonuses {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::range_category::RangeCategory {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.range_start.into_into_dart().into_dart(),
            self.range_end.into_into_dart().into_dart(),
            self.column_index.into_into_dart().into_dart(),
            self.category_key.into_into_dart().into_dart(),
            self.tag.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::range_category::RangeCategory
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::range_category::RangeCategory>
    for crate::range_category::RangeCategory
{
    fn into_into_dart(self) -> crate::range_category::RangeCategory {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::ResistanceAttribute {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.index.into_into_dart().into_dart(),
            self.is_elemental.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::ResistanceAttribute
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::ResistanceAttribute>
    for crate::resistance::ResistanceAttribute
{
    fn into_into_dart(self) -> crate::resistance::ResistanceAttribute {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::ResistanceBonus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.bonus.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::ResistanceBonus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::ResistanceBonus>
    for crate::resistance::ResistanceBonus
{
    fn into_into_dart(self) -> crate::resistance::ResistanceBonus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::ResistanceCorrectionInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.corrections.into_into_dart().into_dart(),
            self.additional_correction.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::ResistanceCorrectionInput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::ResistanceCorrectionInput>
    for crate::resistance::ResistanceCorrectionInput
{
    fn into_into_dart(self) -> crate::resistance::ResistanceCorrectionInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::ResistanceMasterData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.attributes.into_into_dart().into_dart(),
            self.body_color_resistance_rules
                .into_into_dart()
                .into_dart(),
            self.body_color_abnormality_resistance_rules
                .into_into_dart()
                .into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::resistance::ResistanceMasterData
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::ResistanceMasterData>
    for crate::resistance::ResistanceMasterData
{
    fn into_into_dart(self) -> crate::resistance::ResistanceMasterData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::resistance::StatBonus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.hp.into_into_dart().into_dart(),
            self.ap.into_into_dart().into_dart(),
            self.attack.into_into_dart().into_dart(),
            self.defense.into_into_dart().into_dart(),
            self.speed.into_into_dart().into_dart(),
            self.evasion_rate.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::resistance::StatBonus {}
impl flutter_rust_bridge::IntoIntoDart<crate::resistance::StatBonus>
    for crate::resistance::StatBonus
{
    fn into_into_dart(self) -> crate::resistance::StatBonus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::status_match::StatusCriterion {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.rows.into_into_dart().into_dart(),
            self.target_value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::status_match::StatusCriterion
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::status_match::StatusCriterion>
    for crate::status_match::StatusCriterion
{
    fn into_into_dart(self) -> crate::status_match::StatusCriterion {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::status_match::StatusMatch {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.group.into_into_dart().into_dart(),
            self.line_offset.into_into_dart().into_dart(),
            self.column_index.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::status_match::StatusMatch
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::status_match::StatusMatch>
    for crate::status_match::StatusMatch
{
    fn into_into_dart(self) -> crate::status_match::StatusMatch {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::table_row::TableRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.group.into_into_dart().into_dart(),
            self.line_offset.into_into_dart().into_dart(),
            self.values.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::table_row::TableRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::table_row::TableRow> for crate::table_row::TableRow {
    fn into_into_dart(self) -> crate::table_row::TableRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::category_grid::ValueCell {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.column_index.into_into_dart().into_dart(),
            self.line_offset.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.is_match.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::category_grid::ValueCell
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::category_grid::ValueCell>
    for crate::category_grid::ValueCell
{
    fn into_into_dart(self) -> crate::category_grid::ValueCell {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::resistance::AbnormalityResistance {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.abnormality_id, serializer);
        <i32>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for crate::resistance::AttributeResistance {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.attribute_id, serializer);
        <i32>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for crate::resistance::AttributeResistanceBonus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.attribute_id, serializer);
        <i32>::sse_encode(self.bonus, serializer);
    }
}

impl SseEncode for crate::resistance::BodyColorAbnormalityResistanceRule {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.color_id, serializer);
        <Vec<crate::resistance::ResistanceBonus>>::sse_encode(
            self.abnormality_resistance_bonuses,
            serializer,
        );
    }
}

impl SseEncode for crate::resistance::BodyColorResistanceRule {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.color_id, serializer);
        <Vec<crate::resistance::AttributeResistanceBonus>>::sse_encode(
            self.attribute_resistance_bonuses,
            serializer,
        );
    }
}

impl SseEncode for crate::resistance::BodyColorSelection {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.body_colors, serializer);
        <bool>::sse_encode(self.is_sp_color, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::category_grid::CategoryCell {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.category_id, serializer);
        <i32>::sse_encode(self.range_start, serializer);
        <i32>::sse_encode(self.range_end, serializer);
        <i32>::sse_encode(self.column_index, serializer);
        <String>::sse_encode(self.category_key, serializer);
        <Option<String>>::sse_encode(self.tag, serializer);
        <Vec<i32>>::sse_encode(self.live_values, serializer);
        <bool>::sse_encode(self.is_match, serializer);
    }
}

impl SseEncode for crate::category_grid::CategoryGrid {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::category_grid::CategoryCell>>::sse_encode(self.category_cells, serializer);
        <Vec<crate::category_grid::ValueCell>>::sse_encode(self.value_cells, serializer);
    }
}

impl SseEncode for crate::category_grid::CategoryGridRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::range_category::RangeCategory>>::sse_encode(self.categories, serializer);
        <Vec<crate::table_row::TableRow>>::sse_encode(self.primary_rows, serializer);
        <Vec<crate::table_row::TableRow>>::sse_encode(self.companion_rows, serializer);
        <i32>::sse_encode(self.match_column_index, serializer);
        <i32>::sse_encode(self.match_line_offset, serializer);
        <i32>::sse_encode(self.match_value, serializer);
    }
}

impl SseEncode for crate::range_category::CategoryMatch {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.category_key, serializer);
        <Option<String>>::sse_encode(self.tag, serializer);
        <i32>::sse_encode(self.range_start, serializer);
        <i32>::sse_encode(self.range_end, serializer);
    }
}

impl SseEncode for crate::table_row::ColumnEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.value, serializer);
        <i32>::sse_encode(self.line_offset, serializer);
    }
}

impl SseEncode for crate::resistance::CorrectionBonuses {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::resistance::StatBonus>::sse_encode(self.stat_bonus, serializer);
        <Vec<crate::resistance::ResistanceBonus>>::sse_encode(
            self.abnormality_resistance_bonuses,
            serializer,
        );
        <Vec<crate::resistance::AttributeResistanceBonus>>::sse_encode(
            self.attribute_resistance_bonuses,
            serializer,
        );
    }
}

impl SseEncode for crate::resistance::DenpaMenResistances {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::resistance::AbnormalityResistance>>::sse_encode(
            self.abnormality_resistances,
            serializer,
        );
        <Vec<crate::resistance::AttributeResistance>>::sse_encode(
            self.attribute_resistance,
            serializer,
        );
    }
}

impl SseEncode for crate::resistance::HeadShapeResistanceBonuses {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::resistance::ResistanceBonus>>::sse_encode(
            self.abnormality_resistance_bonuses,
            serializer,
        );
        <Vec<crate::resistance::AttributeResistanceBonus>>::sse_encode(
            self.attribute_resistance_bonuses,
            serializer,
        );
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::resistance::AbnormalityResistance> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::resistance::AbnormalityResistance>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::resistance::AttributeResistance> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::resistance::AttributeResistance>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::resistance::AttributeResistanceBonus> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::resistance::AttributeResistanceBonus>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::resistance::BodyColorAbnormalityResistanceRule> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::resistance::BodyColorAbnormalityResistanceRule>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::resistance::BodyColorResistanceRule> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::resistance::BodyColorResistanceRule>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::category_grid::CategoryCell> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::category_grid::CategoryCell>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::range_category::CategoryMatch> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::range_category::CategoryMatch>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::table_row::ColumnEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::table_row::ColumnEntry>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::resistance::CorrectionBonuses> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::resistance::CorrectionBonuses>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<Vec<crate::table_row::ColumnEntry>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <Vec<crate::table_row::ColumnEntry>>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<Option<i32>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <Option<i32>>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <i32>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::range_category::RangeCategory> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::range_category::RangeCategory>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::resistance::ResistanceAttribute> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::resistance::ResistanceAttribute>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::resistance::ResistanceBonus> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::resistance::ResistanceBonus>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::status_match::StatusCriterion> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::status_match::StatusCriterion>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::status_match::StatusMatch> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::status_match::StatusMatch>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::table_row::TableRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::table_row::TableRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::category_grid::ValueCell> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::category_grid::ValueCell>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::resistance::BodyColorSelection> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::resistance::BodyColorSelection>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::range_category::RangeCategory {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <i32>::sse_encode(self.range_start, serializer);
        <i32>::sse_encode(self.range_end, serializer);
        <i32>::sse_encode(self.column_index, serializer);
        <String>::sse_encode(self.category_key, serializer);
        <Option<String>>::sse_encode(self.tag, serializer);
    }
}

impl SseEncode for crate::resistance::ResistanceAttribute {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <i32>::sse_encode(self.index, serializer);
        <bool>::sse_encode(self.is_elemental, serializer);
    }
}

impl SseEncode for crate::resistance::ResistanceBonus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <i32>::sse_encode(self.bonus, serializer);
    }
}

impl SseEncode for crate::resistance::ResistanceCorrectionInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::resistance::CorrectionBonuses>>::sse_encode(self.corrections, serializer);
        <crate::resistance::CorrectionBonuses>::sse_encode(self.additional_correction, serializer);
    }
}

impl SseEncode for crate::resistance::ResistanceMasterData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::resistance::ResistanceAttribute>>::sse_encode(self.attributes, serializer);
        <Vec<crate::resistance::BodyColorResistanceRule>>::sse_encode(
            self.body_color_resistance_rules,
            serializer,
        );
        <Vec<crate::resistance::BodyColorAbnormalityResistanceRule>>::sse_encode(
            self.body_color_abnormality_resistance_rules,
            serializer,
        );
    }
}

impl SseEncode for crate::resistance::StatBonus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.hp, serializer);
        <i32>::sse_encode(self.ap, serializer);
        <i32>::sse_encode(self.attack, serializer);
        <i32>::sse_encode(self.defense, serializer);
        <i32>::sse_encode(self.speed, serializer);
        <i32>::sse_encode(self.evasion_rate, serializer);
    }
}

impl SseEncode for crate::status_match::StatusCriterion {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::table_row::TableRow>>::sse_encode(self.rows, serializer);
        <i32>::sse_encode(self.target_value, serializer);
    }
}

impl SseEncode for crate::status_match::StatusMatch {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.group, serializer);
        <i32>::sse_encode(self.line_offset, serializer);
        <i32>::sse_encode(self.column_index, serializer);
    }
}

impl SseEncode for crate::table_row::TableRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.group, serializer);
        <i32>::sse_encode(self.line_offset, serializer);
        <Vec<Option<i32>>>::sse_encode(self.values, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::category_grid::ValueCell {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.column_index, serializer);
        <i32>::sse_encode(self.line_offset, serializer);
        <i32>::sse_encode(self.value, serializer);
        <bool>::sse_encode(self.is_match, serializer);
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
