// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'range_category.dart';
import 'table_row.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Merges adjacent same-column, same-category, same-tag rows into one
/// wider range, without touching the underlying data.
List<RangeCategory> compactCategories({
  required List<RangeCategory> categories,
}) => RustLib.instance.api.crateCategoryGridCompactCategories(
  categories: categories,
);

/// Builds the "matching location" grid: every category paired with the
/// real values that fall in its range, plus the companion table's
/// values, each flagged with whether it is the cell that was matched.
CategoryGrid buildCategoryGrid({required CategoryGridRequest request}) =>
    RustLib.instance.api.crateCategoryGridBuildCategoryGrid(request: request);

/// One legend cell: a category range paired with which real values (from
/// `primary_rows`) actually fall in it.
class CategoryCell {
  final String categoryId;
  final int rangeStart;
  final int rangeEnd;
  final int columnIndex;
  final String categoryKey;
  final String? tag;
  final Int32List liveValues;
  final bool isMatch;

  const CategoryCell({
    required this.categoryId,
    required this.rangeStart,
    required this.rangeEnd,
    required this.columnIndex,
    required this.categoryKey,
    this.tag,
    required this.liveValues,
    required this.isMatch,
  });

  @override
  int get hashCode =>
      categoryId.hashCode ^
      rangeStart.hashCode ^
      rangeEnd.hashCode ^
      columnIndex.hashCode ^
      categoryKey.hashCode ^
      tag.hashCode ^
      liveValues.hashCode ^
      isMatch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryCell &&
          runtimeType == other.runtimeType &&
          categoryId == other.categoryId &&
          rangeStart == other.rangeStart &&
          rangeEnd == other.rangeEnd &&
          columnIndex == other.columnIndex &&
          categoryKey == other.categoryKey &&
          tag == other.tag &&
          liveValues == other.liveValues &&
          isMatch == other.isMatch;
}

class CategoryGrid {
  final List<CategoryCell> categoryCells;
  final List<ValueCell> valueCells;

  const CategoryGrid({required this.categoryCells, required this.valueCells});

  @override
  int get hashCode => categoryCells.hashCode ^ valueCells.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryGrid &&
          runtimeType == other.runtimeType &&
          categoryCells == other.categoryCells &&
          valueCells == other.valueCells;
}

/// `primary_rows` are matched against each category's range; `companion_rows`
/// are shown alongside for context only (e.g. a second status table).
class CategoryGridRequest {
  final List<RangeCategory> categories;
  final List<TableRow> primaryRows;
  final List<TableRow> companionRows;
  final int matchColumnIndex;
  final int matchLineOffset;
  final int matchValue;

  const CategoryGridRequest({
    required this.categories,
    required this.primaryRows,
    required this.companionRows,
    required this.matchColumnIndex,
    required this.matchLineOffset,
    required this.matchValue,
  });

  @override
  int get hashCode =>
      categories.hashCode ^
      primaryRows.hashCode ^
      companionRows.hashCode ^
      matchColumnIndex.hashCode ^
      matchLineOffset.hashCode ^
      matchValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryGridRequest &&
          runtimeType == other.runtimeType &&
          categories == other.categories &&
          primaryRows == other.primaryRows &&
          companionRows == other.companionRows &&
          matchColumnIndex == other.matchColumnIndex &&
          matchLineOffset == other.matchLineOffset &&
          matchValue == other.matchValue;
}

/// One cell of the companion table, flattened per column.
class ValueCell {
  final int columnIndex;
  final int lineOffset;
  final int value;
  final bool isMatch;

  const ValueCell({
    required this.columnIndex,
    required this.lineOffset,
    required this.value,
    required this.isMatch,
  });

  @override
  int get hashCode =>
      columnIndex.hashCode ^
      lineOffset.hashCode ^
      value.hashCode ^
      isMatch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValueCell &&
          runtimeType == other.runtimeType &&
          columnIndex == other.columnIndex &&
          lineOffset == other.lineOffset &&
          value == other.value &&
          isMatch == other.isMatch;
}
