// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'category_grid.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'range_category.dart';
import 'resistance.dart';
import 'status_match.dart';
import 'table_row.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1391955981;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'denpamemo_logics',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  CategoryGrid crateCategoryGridBuildCategoryGrid({
    required CategoryGridRequest request,
  });

  List<AttributeResistance> crateResistanceCalculateAttributeResistance({
    required BodyColorSelection selection,
    required ResistanceMasterData masterData,
  });

  List<AbnormalityResistance>
  crateResistanceCalculateColorAbnormalityResistance({
    required BodyColorSelection selection,
    required ResistanceMasterData masterData,
  });

  StatBonus crateResistanceCalculateCorrectionStatBonus({
    required ResistanceCorrectionInput input,
  });

  DenpaMenResistances crateResistanceCalculateDenpaMenResistances({
    required BodyColorSelection selection,
    required HeadShapeResistanceBonuses headShape,
    required ResistanceMasterData masterData,
  });

  List<List<ColumnEntry>> crateTableRowCollectColumns({
    required List<TableRow> rows,
  });

  List<RangeCategory> crateCategoryGridCompactCategories({
    required List<RangeCategory> categories,
  });

  BodyColorSelection? crateResistanceFindColorCombination({
    required List<AttributeResistance> target,
    required ResistanceMasterData masterData,
  });

  List<StatusMatch> crateStatusMatchFindMatchingColumns({
    required StatusCriterion primary,
    required List<StatusCriterion> others,
  });

  List<CategoryMatch> crateRangeCategoryResolveCategories({
    required List<RangeCategory> categories,
    required int value,
    required int columnIndex,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  CategoryGrid crateCategoryGridBuildCategoryGrid({
    required CategoryGridRequest request,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_category_grid_request(request, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_category_grid,
          decodeErrorData: null,
        ),
        constMeta: kCrateCategoryGridBuildCategoryGridConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCategoryGridBuildCategoryGridConstMeta =>
      const TaskConstMeta(
        debugName: "build_category_grid",
        argNames: ["request"],
      );

  @override
  List<AttributeResistance> crateResistanceCalculateAttributeResistance({
    required BodyColorSelection selection,
    required ResistanceMasterData masterData,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_body_color_selection(selection, serializer);
          sse_encode_box_autoadd_resistance_master_data(masterData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_attribute_resistance,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateResistanceCalculateAttributeResistanceConstMeta,
        argValues: [selection, masterData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateResistanceCalculateAttributeResistanceConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_attribute_resistance",
        argNames: ["selection", "masterData"],
      );

  @override
  List<AbnormalityResistance>
  crateResistanceCalculateColorAbnormalityResistance({
    required BodyColorSelection selection,
    required ResistanceMasterData masterData,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_body_color_selection(selection, serializer);
          sse_encode_box_autoadd_resistance_master_data(masterData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_abnormality_resistance,
          decodeErrorData: null,
        ),
        constMeta: kCrateResistanceCalculateColorAbnormalityResistanceConstMeta,
        argValues: [selection, masterData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateResistanceCalculateColorAbnormalityResistanceConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_color_abnormality_resistance",
        argNames: ["selection", "masterData"],
      );

  @override
  StatBonus crateResistanceCalculateCorrectionStatBonus({
    required ResistanceCorrectionInput input,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_resistance_correction_input(input, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stat_bonus,
          decodeErrorData: null,
        ),
        constMeta: kCrateResistanceCalculateCorrectionStatBonusConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateResistanceCalculateCorrectionStatBonusConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_correction_stat_bonus",
        argNames: ["input"],
      );

  @override
  DenpaMenResistances crateResistanceCalculateDenpaMenResistances({
    required BodyColorSelection selection,
    required HeadShapeResistanceBonuses headShape,
    required ResistanceMasterData masterData,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_body_color_selection(selection, serializer);
          sse_encode_box_autoadd_head_shape_resistance_bonuses(
            headShape,
            serializer,
          );
          sse_encode_box_autoadd_resistance_master_data(masterData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_denpa_men_resistances,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateResistanceCalculateDenpaMenResistancesConstMeta,
        argValues: [selection, headShape, masterData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateResistanceCalculateDenpaMenResistancesConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_denpa_men_resistances",
        argNames: ["selection", "headShape", "masterData"],
      );

  @override
  List<List<ColumnEntry>> crateTableRowCollectColumns({
    required List<TableRow> rows,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_table_row(rows, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_column_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateTableRowCollectColumnsConstMeta,
        argValues: [rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTableRowCollectColumnsConstMeta =>
      const TaskConstMeta(debugName: "collect_columns", argNames: ["rows"]);

  @override
  List<RangeCategory> crateCategoryGridCompactCategories({
    required List<RangeCategory> categories,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_range_category(categories, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_range_category,
          decodeErrorData: null,
        ),
        constMeta: kCrateCategoryGridCompactCategoriesConstMeta,
        argValues: [categories],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCategoryGridCompactCategoriesConstMeta =>
      const TaskConstMeta(
        debugName: "compact_categories",
        argNames: ["categories"],
      );

  @override
  BodyColorSelection? crateResistanceFindColorCombination({
    required List<AttributeResistance> target,
    required ResistanceMasterData masterData,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_attribute_resistance(target, serializer);
          sse_encode_box_autoadd_resistance_master_data(masterData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_body_color_selection,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateResistanceFindColorCombinationConstMeta,
        argValues: [target, masterData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateResistanceFindColorCombinationConstMeta =>
      const TaskConstMeta(
        debugName: "find_color_combination",
        argNames: ["target", "masterData"],
      );

  @override
  List<StatusMatch> crateStatusMatchFindMatchingColumns({
    required StatusCriterion primary,
    required List<StatusCriterion> others,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_status_criterion(primary, serializer);
          sse_encode_list_status_criterion(others, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_status_match,
          decodeErrorData: null,
        ),
        constMeta: kCrateStatusMatchFindMatchingColumnsConstMeta,
        argValues: [primary, others],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateStatusMatchFindMatchingColumnsConstMeta =>
      const TaskConstMeta(
        debugName: "find_matching_columns",
        argNames: ["primary", "others"],
      );

  @override
  List<CategoryMatch> crateRangeCategoryResolveCategories({
    required List<RangeCategory> categories,
    required int value,
    required int columnIndex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_range_category(categories, serializer);
          sse_encode_i_32(value, serializer);
          sse_encode_i_32(columnIndex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_category_match,
          decodeErrorData: null,
        ),
        constMeta: kCrateRangeCategoryResolveCategoriesConstMeta,
        argValues: [categories, value, columnIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateRangeCategoryResolveCategoriesConstMeta =>
      const TaskConstMeta(
        debugName: "resolve_categories",
        argNames: ["categories", "value", "columnIndex"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AbnormalityResistance dco_decode_abnormality_resistance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AbnormalityResistance(
      abnormalityId: dco_decode_String(arr[0]),
      value: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  AttributeResistance dco_decode_attribute_resistance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AttributeResistance(
      attributeId: dco_decode_String(arr[0]),
      value: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  AttributeResistanceBonus dco_decode_attribute_resistance_bonus(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AttributeResistanceBonus(
      attributeId: dco_decode_String(arr[0]),
      bonus: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  BodyColorAbnormalityResistanceRule
  dco_decode_body_color_abnormality_resistance_rule(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BodyColorAbnormalityResistanceRule(
      colorId: dco_decode_String(arr[0]),
      abnormalityResistanceBonuses: dco_decode_list_resistance_bonus(arr[1]),
    );
  }

  @protected
  BodyColorResistanceRule dco_decode_body_color_resistance_rule(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BodyColorResistanceRule(
      colorId: dco_decode_String(arr[0]),
      attributeResistanceBonuses: dco_decode_list_attribute_resistance_bonus(
        arr[1],
      ),
    );
  }

  @protected
  BodyColorSelection dco_decode_body_color_selection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BodyColorSelection(
      bodyColors: dco_decode_list_String(arr[0]),
      isSpColor: dco_decode_bool(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BodyColorSelection dco_decode_box_autoadd_body_color_selection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_body_color_selection(raw);
  }

  @protected
  CategoryGridRequest dco_decode_box_autoadd_category_grid_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_category_grid_request(raw);
  }

  @protected
  HeadShapeResistanceBonuses
  dco_decode_box_autoadd_head_shape_resistance_bonuses(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_head_shape_resistance_bonuses(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ResistanceCorrectionInput dco_decode_box_autoadd_resistance_correction_input(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_resistance_correction_input(raw);
  }

  @protected
  ResistanceMasterData dco_decode_box_autoadd_resistance_master_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_resistance_master_data(raw);
  }

  @protected
  StatusCriterion dco_decode_box_autoadd_status_criterion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_status_criterion(raw);
  }

  @protected
  CategoryCell dco_decode_category_cell(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return CategoryCell(
      categoryId: dco_decode_String(arr[0]),
      rangeStart: dco_decode_i_32(arr[1]),
      rangeEnd: dco_decode_i_32(arr[2]),
      columnIndex: dco_decode_i_32(arr[3]),
      categoryKey: dco_decode_String(arr[4]),
      tag: dco_decode_opt_String(arr[5]),
      liveValues: dco_decode_list_prim_i_32_strict(arr[6]),
      isMatch: dco_decode_bool(arr[7]),
    );
  }

  @protected
  CategoryGrid dco_decode_category_grid(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CategoryGrid(
      categoryCells: dco_decode_list_category_cell(arr[0]),
      valueCells: dco_decode_list_value_cell(arr[1]),
    );
  }

  @protected
  CategoryGridRequest dco_decode_category_grid_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CategoryGridRequest(
      categories: dco_decode_list_range_category(arr[0]),
      primaryRows: dco_decode_list_table_row(arr[1]),
      companionRows: dco_decode_list_table_row(arr[2]),
      matchColumnIndex: dco_decode_i_32(arr[3]),
      matchLineOffset: dco_decode_i_32(arr[4]),
      matchValue: dco_decode_i_32(arr[5]),
    );
  }

  @protected
  CategoryMatch dco_decode_category_match(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CategoryMatch(
      categoryKey: dco_decode_String(arr[0]),
      tag: dco_decode_opt_String(arr[1]),
      rangeStart: dco_decode_i_32(arr[2]),
      rangeEnd: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  ColumnEntry dco_decode_column_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ColumnEntry(
      value: dco_decode_i_32(arr[0]),
      lineOffset: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  CorrectionBonuses dco_decode_correction_bonuses(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CorrectionBonuses(
      statBonus: dco_decode_stat_bonus(arr[0]),
      abnormalityResistanceBonuses: dco_decode_list_resistance_bonus(arr[1]),
      attributeResistanceBonuses: dco_decode_list_attribute_resistance_bonus(
        arr[2],
      ),
    );
  }

  @protected
  DenpaMenResistances dco_decode_denpa_men_resistances(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DenpaMenResistances(
      abnormalityResistances: dco_decode_list_abnormality_resistance(arr[0]),
      attributeResistance: dco_decode_list_attribute_resistance(arr[1]),
    );
  }

  @protected
  HeadShapeResistanceBonuses dco_decode_head_shape_resistance_bonuses(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HeadShapeResistanceBonuses(
      abnormalityResistanceBonuses: dco_decode_list_resistance_bonus(arr[0]),
      attributeResistanceBonuses: dco_decode_list_attribute_resistance_bonus(
        arr[1],
      ),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AbnormalityResistance> dco_decode_list_abnormality_resistance(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_abnormality_resistance)
        .toList();
  }

  @protected
  List<AttributeResistance> dco_decode_list_attribute_resistance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_attribute_resistance).toList();
  }

  @protected
  List<AttributeResistanceBonus> dco_decode_list_attribute_resistance_bonus(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_attribute_resistance_bonus)
        .toList();
  }

  @protected
  List<BodyColorAbnormalityResistanceRule>
  dco_decode_list_body_color_abnormality_resistance_rule(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_body_color_abnormality_resistance_rule)
        .toList();
  }

  @protected
  List<BodyColorResistanceRule> dco_decode_list_body_color_resistance_rule(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_body_color_resistance_rule)
        .toList();
  }

  @protected
  List<CategoryCell> dco_decode_list_category_cell(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_category_cell).toList();
  }

  @protected
  List<CategoryMatch> dco_decode_list_category_match(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_category_match).toList();
  }

  @protected
  List<ColumnEntry> dco_decode_list_column_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_column_entry).toList();
  }

  @protected
  List<CorrectionBonuses> dco_decode_list_correction_bonuses(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_correction_bonuses).toList();
  }

  @protected
  List<List<ColumnEntry>> dco_decode_list_list_column_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_column_entry).toList();
  }

  @protected
  List<int?> dco_decode_list_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_opt_box_autoadd_i_32).toList();
  }

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RangeCategory> dco_decode_list_range_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_range_category).toList();
  }

  @protected
  List<ResistanceAttribute> dco_decode_list_resistance_attribute(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_resistance_attribute).toList();
  }

  @protected
  List<ResistanceBonus> dco_decode_list_resistance_bonus(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_resistance_bonus).toList();
  }

  @protected
  List<StatusCriterion> dco_decode_list_status_criterion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_status_criterion).toList();
  }

  @protected
  List<StatusMatch> dco_decode_list_status_match(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_status_match).toList();
  }

  @protected
  List<TableRow> dco_decode_list_table_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_table_row).toList();
  }

  @protected
  List<ValueCell> dco_decode_list_value_cell(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_value_cell).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BodyColorSelection? dco_decode_opt_box_autoadd_body_color_selection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_body_color_selection(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  RangeCategory dco_decode_range_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RangeCategory(
      id: dco_decode_String(arr[0]),
      rangeStart: dco_decode_i_32(arr[1]),
      rangeEnd: dco_decode_i_32(arr[2]),
      columnIndex: dco_decode_i_32(arr[3]),
      categoryKey: dco_decode_String(arr[4]),
      tag: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  ResistanceAttribute dco_decode_resistance_attribute(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ResistanceAttribute(
      id: dco_decode_String(arr[0]),
      index: dco_decode_i_32(arr[1]),
      isElemental: dco_decode_bool(arr[2]),
    );
  }

  @protected
  ResistanceBonus dco_decode_resistance_bonus(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ResistanceBonus(
      id: dco_decode_String(arr[0]),
      bonus: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  ResistanceCorrectionInput dco_decode_resistance_correction_input(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ResistanceCorrectionInput(
      corrections: dco_decode_list_correction_bonuses(arr[0]),
      additionalCorrection: dco_decode_correction_bonuses(arr[1]),
    );
  }

  @protected
  ResistanceMasterData dco_decode_resistance_master_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ResistanceMasterData(
      attributes: dco_decode_list_resistance_attribute(arr[0]),
      bodyColorResistanceRules: dco_decode_list_body_color_resistance_rule(
        arr[1],
      ),
      bodyColorAbnormalityResistanceRules:
          dco_decode_list_body_color_abnormality_resistance_rule(arr[2]),
    );
  }

  @protected
  StatBonus dco_decode_stat_bonus(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return StatBonus(
      hp: dco_decode_i_32(arr[0]),
      ap: dco_decode_i_32(arr[1]),
      attack: dco_decode_i_32(arr[2]),
      defense: dco_decode_i_32(arr[3]),
      speed: dco_decode_i_32(arr[4]),
      evasionRate: dco_decode_i_32(arr[5]),
    );
  }

  @protected
  StatusCriterion dco_decode_status_criterion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StatusCriterion(
      rows: dco_decode_list_table_row(arr[0]),
      targetValue: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  StatusMatch dco_decode_status_match(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StatusMatch(
      group: dco_decode_list_String(arr[0]),
      lineOffset: dco_decode_i_32(arr[1]),
      columnIndex: dco_decode_i_32(arr[2]),
    );
  }

  @protected
  TableRow dco_decode_table_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TableRow(
      group: dco_decode_list_String(arr[0]),
      lineOffset: dco_decode_i_32(arr[1]),
      values: dco_decode_list_opt_box_autoadd_i_32(arr[2]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  ValueCell dco_decode_value_cell(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ValueCell(
      columnIndex: dco_decode_i_32(arr[0]),
      lineOffset: dco_decode_i_32(arr[1]),
      value: dco_decode_i_32(arr[2]),
      isMatch: dco_decode_bool(arr[3]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AbnormalityResistance sse_decode_abnormality_resistance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_abnormalityId = sse_decode_String(deserializer);
    var var_value = sse_decode_i_32(deserializer);
    return AbnormalityResistance(
      abnormalityId: var_abnormalityId,
      value: var_value,
    );
  }

  @protected
  AttributeResistance sse_decode_attribute_resistance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_attributeId = sse_decode_String(deserializer);
    var var_value = sse_decode_i_32(deserializer);
    return AttributeResistance(attributeId: var_attributeId, value: var_value);
  }

  @protected
  AttributeResistanceBonus sse_decode_attribute_resistance_bonus(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_attributeId = sse_decode_String(deserializer);
    var var_bonus = sse_decode_i_32(deserializer);
    return AttributeResistanceBonus(
      attributeId: var_attributeId,
      bonus: var_bonus,
    );
  }

  @protected
  BodyColorAbnormalityResistanceRule
  sse_decode_body_color_abnormality_resistance_rule(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_colorId = sse_decode_String(deserializer);
    var var_abnormalityResistanceBonuses = sse_decode_list_resistance_bonus(
      deserializer,
    );
    return BodyColorAbnormalityResistanceRule(
      colorId: var_colorId,
      abnormalityResistanceBonuses: var_abnormalityResistanceBonuses,
    );
  }

  @protected
  BodyColorResistanceRule sse_decode_body_color_resistance_rule(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_colorId = sse_decode_String(deserializer);
    var var_attributeResistanceBonuses =
        sse_decode_list_attribute_resistance_bonus(deserializer);
    return BodyColorResistanceRule(
      colorId: var_colorId,
      attributeResistanceBonuses: var_attributeResistanceBonuses,
    );
  }

  @protected
  BodyColorSelection sse_decode_body_color_selection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bodyColors = sse_decode_list_String(deserializer);
    var var_isSpColor = sse_decode_bool(deserializer);
    return BodyColorSelection(
      bodyColors: var_bodyColors,
      isSpColor: var_isSpColor,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BodyColorSelection sse_decode_box_autoadd_body_color_selection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_body_color_selection(deserializer));
  }

  @protected
  CategoryGridRequest sse_decode_box_autoadd_category_grid_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_category_grid_request(deserializer));
  }

  @protected
  HeadShapeResistanceBonuses
  sse_decode_box_autoadd_head_shape_resistance_bonuses(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_head_shape_resistance_bonuses(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  ResistanceCorrectionInput sse_decode_box_autoadd_resistance_correction_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_resistance_correction_input(deserializer));
  }

  @protected
  ResistanceMasterData sse_decode_box_autoadd_resistance_master_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_resistance_master_data(deserializer));
  }

  @protected
  StatusCriterion sse_decode_box_autoadd_status_criterion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_status_criterion(deserializer));
  }

  @protected
  CategoryCell sse_decode_category_cell(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_categoryId = sse_decode_String(deserializer);
    var var_rangeStart = sse_decode_i_32(deserializer);
    var var_rangeEnd = sse_decode_i_32(deserializer);
    var var_columnIndex = sse_decode_i_32(deserializer);
    var var_categoryKey = sse_decode_String(deserializer);
    var var_tag = sse_decode_opt_String(deserializer);
    var var_liveValues = sse_decode_list_prim_i_32_strict(deserializer);
    var var_isMatch = sse_decode_bool(deserializer);
    return CategoryCell(
      categoryId: var_categoryId,
      rangeStart: var_rangeStart,
      rangeEnd: var_rangeEnd,
      columnIndex: var_columnIndex,
      categoryKey: var_categoryKey,
      tag: var_tag,
      liveValues: var_liveValues,
      isMatch: var_isMatch,
    );
  }

  @protected
  CategoryGrid sse_decode_category_grid(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_categoryCells = sse_decode_list_category_cell(deserializer);
    var var_valueCells = sse_decode_list_value_cell(deserializer);
    return CategoryGrid(
      categoryCells: var_categoryCells,
      valueCells: var_valueCells,
    );
  }

  @protected
  CategoryGridRequest sse_decode_category_grid_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_categories = sse_decode_list_range_category(deserializer);
    var var_primaryRows = sse_decode_list_table_row(deserializer);
    var var_companionRows = sse_decode_list_table_row(deserializer);
    var var_matchColumnIndex = sse_decode_i_32(deserializer);
    var var_matchLineOffset = sse_decode_i_32(deserializer);
    var var_matchValue = sse_decode_i_32(deserializer);
    return CategoryGridRequest(
      categories: var_categories,
      primaryRows: var_primaryRows,
      companionRows: var_companionRows,
      matchColumnIndex: var_matchColumnIndex,
      matchLineOffset: var_matchLineOffset,
      matchValue: var_matchValue,
    );
  }

  @protected
  CategoryMatch sse_decode_category_match(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_categoryKey = sse_decode_String(deserializer);
    var var_tag = sse_decode_opt_String(deserializer);
    var var_rangeStart = sse_decode_i_32(deserializer);
    var var_rangeEnd = sse_decode_i_32(deserializer);
    return CategoryMatch(
      categoryKey: var_categoryKey,
      tag: var_tag,
      rangeStart: var_rangeStart,
      rangeEnd: var_rangeEnd,
    );
  }

  @protected
  ColumnEntry sse_decode_column_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_i_32(deserializer);
    var var_lineOffset = sse_decode_i_32(deserializer);
    return ColumnEntry(value: var_value, lineOffset: var_lineOffset);
  }

  @protected
  CorrectionBonuses sse_decode_correction_bonuses(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_statBonus = sse_decode_stat_bonus(deserializer);
    var var_abnormalityResistanceBonuses = sse_decode_list_resistance_bonus(
      deserializer,
    );
    var var_attributeResistanceBonuses =
        sse_decode_list_attribute_resistance_bonus(deserializer);
    return CorrectionBonuses(
      statBonus: var_statBonus,
      abnormalityResistanceBonuses: var_abnormalityResistanceBonuses,
      attributeResistanceBonuses: var_attributeResistanceBonuses,
    );
  }

  @protected
  DenpaMenResistances sse_decode_denpa_men_resistances(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_abnormalityResistances = sse_decode_list_abnormality_resistance(
      deserializer,
    );
    var var_attributeResistance = sse_decode_list_attribute_resistance(
      deserializer,
    );
    return DenpaMenResistances(
      abnormalityResistances: var_abnormalityResistances,
      attributeResistance: var_attributeResistance,
    );
  }

  @protected
  HeadShapeResistanceBonuses sse_decode_head_shape_resistance_bonuses(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_abnormalityResistanceBonuses = sse_decode_list_resistance_bonus(
      deserializer,
    );
    var var_attributeResistanceBonuses =
        sse_decode_list_attribute_resistance_bonus(deserializer);
    return HeadShapeResistanceBonuses(
      abnormalityResistanceBonuses: var_abnormalityResistanceBonuses,
      attributeResistanceBonuses: var_attributeResistanceBonuses,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AbnormalityResistance> sse_decode_list_abnormality_resistance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AbnormalityResistance>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_abnormality_resistance(deserializer));
    }
    return ans_;
  }

  @protected
  List<AttributeResistance> sse_decode_list_attribute_resistance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AttributeResistance>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_attribute_resistance(deserializer));
    }
    return ans_;
  }

  @protected
  List<AttributeResistanceBonus> sse_decode_list_attribute_resistance_bonus(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AttributeResistanceBonus>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_attribute_resistance_bonus(deserializer));
    }
    return ans_;
  }

  @protected
  List<BodyColorAbnormalityResistanceRule>
  sse_decode_list_body_color_abnormality_resistance_rule(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BodyColorAbnormalityResistanceRule>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_body_color_abnormality_resistance_rule(deserializer));
    }
    return ans_;
  }

  @protected
  List<BodyColorResistanceRule> sse_decode_list_body_color_resistance_rule(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BodyColorResistanceRule>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_body_color_resistance_rule(deserializer));
    }
    return ans_;
  }

  @protected
  List<CategoryCell> sse_decode_list_category_cell(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CategoryCell>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_category_cell(deserializer));
    }
    return ans_;
  }

  @protected
  List<CategoryMatch> sse_decode_list_category_match(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CategoryMatch>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_category_match(deserializer));
    }
    return ans_;
  }

  @protected
  List<ColumnEntry> sse_decode_list_column_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ColumnEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_column_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<CorrectionBonuses> sse_decode_list_correction_bonuses(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CorrectionBonuses>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_correction_bonuses(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<ColumnEntry>> sse_decode_list_list_column_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <List<ColumnEntry>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_column_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<int?> sse_decode_list_opt_box_autoadd_i_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <int?>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_opt_box_autoadd_i_32(deserializer));
    }
    return ans_;
  }

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RangeCategory> sse_decode_list_range_category(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RangeCategory>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_range_category(deserializer));
    }
    return ans_;
  }

  @protected
  List<ResistanceAttribute> sse_decode_list_resistance_attribute(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ResistanceAttribute>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_resistance_attribute(deserializer));
    }
    return ans_;
  }

  @protected
  List<ResistanceBonus> sse_decode_list_resistance_bonus(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ResistanceBonus>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_resistance_bonus(deserializer));
    }
    return ans_;
  }

  @protected
  List<StatusCriterion> sse_decode_list_status_criterion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StatusCriterion>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_status_criterion(deserializer));
    }
    return ans_;
  }

  @protected
  List<StatusMatch> sse_decode_list_status_match(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StatusMatch>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_status_match(deserializer));
    }
    return ans_;
  }

  @protected
  List<TableRow> sse_decode_list_table_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TableRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_table_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<ValueCell> sse_decode_list_value_cell(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ValueCell>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_value_cell(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BodyColorSelection? sse_decode_opt_box_autoadd_body_color_selection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_body_color_selection(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RangeCategory sse_decode_range_category(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_rangeStart = sse_decode_i_32(deserializer);
    var var_rangeEnd = sse_decode_i_32(deserializer);
    var var_columnIndex = sse_decode_i_32(deserializer);
    var var_categoryKey = sse_decode_String(deserializer);
    var var_tag = sse_decode_opt_String(deserializer);
    return RangeCategory(
      id: var_id,
      rangeStart: var_rangeStart,
      rangeEnd: var_rangeEnd,
      columnIndex: var_columnIndex,
      categoryKey: var_categoryKey,
      tag: var_tag,
    );
  }

  @protected
  ResistanceAttribute sse_decode_resistance_attribute(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_index = sse_decode_i_32(deserializer);
    var var_isElemental = sse_decode_bool(deserializer);
    return ResistanceAttribute(
      id: var_id,
      index: var_index,
      isElemental: var_isElemental,
    );
  }

  @protected
  ResistanceBonus sse_decode_resistance_bonus(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_bonus = sse_decode_i_32(deserializer);
    return ResistanceBonus(id: var_id, bonus: var_bonus);
  }

  @protected
  ResistanceCorrectionInput sse_decode_resistance_correction_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_corrections = sse_decode_list_correction_bonuses(deserializer);
    var var_additionalCorrection = sse_decode_correction_bonuses(deserializer);
    return ResistanceCorrectionInput(
      corrections: var_corrections,
      additionalCorrection: var_additionalCorrection,
    );
  }

  @protected
  ResistanceMasterData sse_decode_resistance_master_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_attributes = sse_decode_list_resistance_attribute(deserializer);
    var var_bodyColorResistanceRules =
        sse_decode_list_body_color_resistance_rule(deserializer);
    var var_bodyColorAbnormalityResistanceRules =
        sse_decode_list_body_color_abnormality_resistance_rule(deserializer);
    return ResistanceMasterData(
      attributes: var_attributes,
      bodyColorResistanceRules: var_bodyColorResistanceRules,
      bodyColorAbnormalityResistanceRules:
          var_bodyColorAbnormalityResistanceRules,
    );
  }

  @protected
  StatBonus sse_decode_stat_bonus(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hp = sse_decode_i_32(deserializer);
    var var_ap = sse_decode_i_32(deserializer);
    var var_attack = sse_decode_i_32(deserializer);
    var var_defense = sse_decode_i_32(deserializer);
    var var_speed = sse_decode_i_32(deserializer);
    var var_evasionRate = sse_decode_i_32(deserializer);
    return StatBonus(
      hp: var_hp,
      ap: var_ap,
      attack: var_attack,
      defense: var_defense,
      speed: var_speed,
      evasionRate: var_evasionRate,
    );
  }

  @protected
  StatusCriterion sse_decode_status_criterion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rows = sse_decode_list_table_row(deserializer);
    var var_targetValue = sse_decode_i_32(deserializer);
    return StatusCriterion(rows: var_rows, targetValue: var_targetValue);
  }

  @protected
  StatusMatch sse_decode_status_match(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_group = sse_decode_list_String(deserializer);
    var var_lineOffset = sse_decode_i_32(deserializer);
    var var_columnIndex = sse_decode_i_32(deserializer);
    return StatusMatch(
      group: var_group,
      lineOffset: var_lineOffset,
      columnIndex: var_columnIndex,
    );
  }

  @protected
  TableRow sse_decode_table_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_group = sse_decode_list_String(deserializer);
    var var_lineOffset = sse_decode_i_32(deserializer);
    var var_values = sse_decode_list_opt_box_autoadd_i_32(deserializer);
    return TableRow(
      group: var_group,
      lineOffset: var_lineOffset,
      values: var_values,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  ValueCell sse_decode_value_cell(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_columnIndex = sse_decode_i_32(deserializer);
    var var_lineOffset = sse_decode_i_32(deserializer);
    var var_value = sse_decode_i_32(deserializer);
    var var_isMatch = sse_decode_bool(deserializer);
    return ValueCell(
      columnIndex: var_columnIndex,
      lineOffset: var_lineOffset,
      value: var_value,
      isMatch: var_isMatch,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_abnormality_resistance(
    AbnormalityResistance self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.abnormalityId, serializer);
    sse_encode_i_32(self.value, serializer);
  }

  @protected
  void sse_encode_attribute_resistance(
    AttributeResistance self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.attributeId, serializer);
    sse_encode_i_32(self.value, serializer);
  }

  @protected
  void sse_encode_attribute_resistance_bonus(
    AttributeResistanceBonus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.attributeId, serializer);
    sse_encode_i_32(self.bonus, serializer);
  }

  @protected
  void sse_encode_body_color_abnormality_resistance_rule(
    BodyColorAbnormalityResistanceRule self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.colorId, serializer);
    sse_encode_list_resistance_bonus(
      self.abnormalityResistanceBonuses,
      serializer,
    );
  }

  @protected
  void sse_encode_body_color_resistance_rule(
    BodyColorResistanceRule self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.colorId, serializer);
    sse_encode_list_attribute_resistance_bonus(
      self.attributeResistanceBonuses,
      serializer,
    );
  }

  @protected
  void sse_encode_body_color_selection(
    BodyColorSelection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.bodyColors, serializer);
    sse_encode_bool(self.isSpColor, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_body_color_selection(
    BodyColorSelection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_body_color_selection(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_category_grid_request(
    CategoryGridRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_category_grid_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_head_shape_resistance_bonuses(
    HeadShapeResistanceBonuses self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_head_shape_resistance_bonuses(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_resistance_correction_input(
    ResistanceCorrectionInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_resistance_correction_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_resistance_master_data(
    ResistanceMasterData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_resistance_master_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_status_criterion(
    StatusCriterion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_status_criterion(self, serializer);
  }

  @protected
  void sse_encode_category_cell(CategoryCell self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.categoryId, serializer);
    sse_encode_i_32(self.rangeStart, serializer);
    sse_encode_i_32(self.rangeEnd, serializer);
    sse_encode_i_32(self.columnIndex, serializer);
    sse_encode_String(self.categoryKey, serializer);
    sse_encode_opt_String(self.tag, serializer);
    sse_encode_list_prim_i_32_strict(self.liveValues, serializer);
    sse_encode_bool(self.isMatch, serializer);
  }

  @protected
  void sse_encode_category_grid(CategoryGrid self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_category_cell(self.categoryCells, serializer);
    sse_encode_list_value_cell(self.valueCells, serializer);
  }

  @protected
  void sse_encode_category_grid_request(
    CategoryGridRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_range_category(self.categories, serializer);
    sse_encode_list_table_row(self.primaryRows, serializer);
    sse_encode_list_table_row(self.companionRows, serializer);
    sse_encode_i_32(self.matchColumnIndex, serializer);
    sse_encode_i_32(self.matchLineOffset, serializer);
    sse_encode_i_32(self.matchValue, serializer);
  }

  @protected
  void sse_encode_category_match(CategoryMatch self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.categoryKey, serializer);
    sse_encode_opt_String(self.tag, serializer);
    sse_encode_i_32(self.rangeStart, serializer);
    sse_encode_i_32(self.rangeEnd, serializer);
  }

  @protected
  void sse_encode_column_entry(ColumnEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.value, serializer);
    sse_encode_i_32(self.lineOffset, serializer);
  }

  @protected
  void sse_encode_correction_bonuses(
    CorrectionBonuses self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_stat_bonus(self.statBonus, serializer);
    sse_encode_list_resistance_bonus(
      self.abnormalityResistanceBonuses,
      serializer,
    );
    sse_encode_list_attribute_resistance_bonus(
      self.attributeResistanceBonuses,
      serializer,
    );
  }

  @protected
  void sse_encode_denpa_men_resistances(
    DenpaMenResistances self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_abnormality_resistance(
      self.abnormalityResistances,
      serializer,
    );
    sse_encode_list_attribute_resistance(self.attributeResistance, serializer);
  }

  @protected
  void sse_encode_head_shape_resistance_bonuses(
    HeadShapeResistanceBonuses self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_resistance_bonus(
      self.abnormalityResistanceBonuses,
      serializer,
    );
    sse_encode_list_attribute_resistance_bonus(
      self.attributeResistanceBonuses,
      serializer,
    );
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_abnormality_resistance(
    List<AbnormalityResistance> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_abnormality_resistance(item, serializer);
    }
  }

  @protected
  void sse_encode_list_attribute_resistance(
    List<AttributeResistance> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_attribute_resistance(item, serializer);
    }
  }

  @protected
  void sse_encode_list_attribute_resistance_bonus(
    List<AttributeResistanceBonus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_attribute_resistance_bonus(item, serializer);
    }
  }

  @protected
  void sse_encode_list_body_color_abnormality_resistance_rule(
    List<BodyColorAbnormalityResistanceRule> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_body_color_abnormality_resistance_rule(item, serializer);
    }
  }

  @protected
  void sse_encode_list_body_color_resistance_rule(
    List<BodyColorResistanceRule> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_body_color_resistance_rule(item, serializer);
    }
  }

  @protected
  void sse_encode_list_category_cell(
    List<CategoryCell> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_category_cell(item, serializer);
    }
  }

  @protected
  void sse_encode_list_category_match(
    List<CategoryMatch> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_category_match(item, serializer);
    }
  }

  @protected
  void sse_encode_list_column_entry(
    List<ColumnEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_column_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_correction_bonuses(
    List<CorrectionBonuses> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_correction_bonuses(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_column_entry(
    List<List<ColumnEntry>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_column_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_opt_box_autoadd_i_32(
    List<int?> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_opt_box_autoadd_i_32(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_range_category(
    List<RangeCategory> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_range_category(item, serializer);
    }
  }

  @protected
  void sse_encode_list_resistance_attribute(
    List<ResistanceAttribute> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_resistance_attribute(item, serializer);
    }
  }

  @protected
  void sse_encode_list_resistance_bonus(
    List<ResistanceBonus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_resistance_bonus(item, serializer);
    }
  }

  @protected
  void sse_encode_list_status_criterion(
    List<StatusCriterion> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_status_criterion(item, serializer);
    }
  }

  @protected
  void sse_encode_list_status_match(
    List<StatusMatch> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_status_match(item, serializer);
    }
  }

  @protected
  void sse_encode_list_table_row(
    List<TableRow> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_table_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_value_cell(
    List<ValueCell> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_value_cell(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_body_color_selection(
    BodyColorSelection? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_body_color_selection(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_range_category(RangeCategory self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_32(self.rangeStart, serializer);
    sse_encode_i_32(self.rangeEnd, serializer);
    sse_encode_i_32(self.columnIndex, serializer);
    sse_encode_String(self.categoryKey, serializer);
    sse_encode_opt_String(self.tag, serializer);
  }

  @protected
  void sse_encode_resistance_attribute(
    ResistanceAttribute self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_32(self.index, serializer);
    sse_encode_bool(self.isElemental, serializer);
  }

  @protected
  void sse_encode_resistance_bonus(
    ResistanceBonus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_32(self.bonus, serializer);
  }

  @protected
  void sse_encode_resistance_correction_input(
    ResistanceCorrectionInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_correction_bonuses(self.corrections, serializer);
    sse_encode_correction_bonuses(self.additionalCorrection, serializer);
  }

  @protected
  void sse_encode_resistance_master_data(
    ResistanceMasterData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_resistance_attribute(self.attributes, serializer);
    sse_encode_list_body_color_resistance_rule(
      self.bodyColorResistanceRules,
      serializer,
    );
    sse_encode_list_body_color_abnormality_resistance_rule(
      self.bodyColorAbnormalityResistanceRules,
      serializer,
    );
  }

  @protected
  void sse_encode_stat_bonus(StatBonus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.hp, serializer);
    sse_encode_i_32(self.ap, serializer);
    sse_encode_i_32(self.attack, serializer);
    sse_encode_i_32(self.defense, serializer);
    sse_encode_i_32(self.speed, serializer);
    sse_encode_i_32(self.evasionRate, serializer);
  }

  @protected
  void sse_encode_status_criterion(
    StatusCriterion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_table_row(self.rows, serializer);
    sse_encode_i_32(self.targetValue, serializer);
  }

  @protected
  void sse_encode_status_match(StatusMatch self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.group, serializer);
    sse_encode_i_32(self.lineOffset, serializer);
    sse_encode_i_32(self.columnIndex, serializer);
  }

  @protected
  void sse_encode_table_row(TableRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.group, serializer);
    sse_encode_i_32(self.lineOffset, serializer);
    sse_encode_list_opt_box_autoadd_i_32(self.values, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_value_cell(ValueCell self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.columnIndex, serializer);
    sse_encode_i_32(self.lineOffset, serializer);
    sse_encode_i_32(self.value, serializer);
    sse_encode_bool(self.isMatch, serializer);
  }
}
