// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'category_grid.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'range_category.dart';
import 'status_match.dart';
import 'table_row.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CategoryGridRequest dco_decode_box_autoadd_category_grid_request(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  StatusCriterion dco_decode_box_autoadd_status_criterion(dynamic raw);

  @protected
  CategoryCell dco_decode_category_cell(dynamic raw);

  @protected
  CategoryGrid dco_decode_category_grid(dynamic raw);

  @protected
  CategoryGridRequest dco_decode_category_grid_request(dynamic raw);

  @protected
  CategoryMatch dco_decode_category_match(dynamic raw);

  @protected
  ColumnEntry dco_decode_column_entry(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CategoryCell> dco_decode_list_category_cell(dynamic raw);

  @protected
  List<CategoryMatch> dco_decode_list_category_match(dynamic raw);

  @protected
  List<ColumnEntry> dco_decode_list_column_entry(dynamic raw);

  @protected
  List<List<ColumnEntry>> dco_decode_list_list_column_entry(dynamic raw);

  @protected
  List<int?> dco_decode_list_opt_box_autoadd_i_32(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RangeCategory> dco_decode_list_range_category(dynamic raw);

  @protected
  List<StatusCriterion> dco_decode_list_status_criterion(dynamic raw);

  @protected
  List<StatusMatch> dco_decode_list_status_match(dynamic raw);

  @protected
  List<TableRow> dco_decode_list_table_row(dynamic raw);

  @protected
  List<ValueCell> dco_decode_list_value_cell(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  RangeCategory dco_decode_range_category(dynamic raw);

  @protected
  StatusCriterion dco_decode_status_criterion(dynamic raw);

  @protected
  StatusMatch dco_decode_status_match(dynamic raw);

  @protected
  TableRow dco_decode_table_row(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  ValueCell dco_decode_value_cell(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CategoryGridRequest sse_decode_box_autoadd_category_grid_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  StatusCriterion sse_decode_box_autoadd_status_criterion(
    SseDeserializer deserializer,
  );

  @protected
  CategoryCell sse_decode_category_cell(SseDeserializer deserializer);

  @protected
  CategoryGrid sse_decode_category_grid(SseDeserializer deserializer);

  @protected
  CategoryGridRequest sse_decode_category_grid_request(
    SseDeserializer deserializer,
  );

  @protected
  CategoryMatch sse_decode_category_match(SseDeserializer deserializer);

  @protected
  ColumnEntry sse_decode_column_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CategoryCell> sse_decode_list_category_cell(
    SseDeserializer deserializer,
  );

  @protected
  List<CategoryMatch> sse_decode_list_category_match(
    SseDeserializer deserializer,
  );

  @protected
  List<ColumnEntry> sse_decode_list_column_entry(SseDeserializer deserializer);

  @protected
  List<List<ColumnEntry>> sse_decode_list_list_column_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<int?> sse_decode_list_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RangeCategory> sse_decode_list_range_category(
    SseDeserializer deserializer,
  );

  @protected
  List<StatusCriterion> sse_decode_list_status_criterion(
    SseDeserializer deserializer,
  );

  @protected
  List<StatusMatch> sse_decode_list_status_match(SseDeserializer deserializer);

  @protected
  List<TableRow> sse_decode_list_table_row(SseDeserializer deserializer);

  @protected
  List<ValueCell> sse_decode_list_value_cell(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  RangeCategory sse_decode_range_category(SseDeserializer deserializer);

  @protected
  StatusCriterion sse_decode_status_criterion(SseDeserializer deserializer);

  @protected
  StatusMatch sse_decode_status_match(SseDeserializer deserializer);

  @protected
  TableRow sse_decode_table_row(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ValueCell sse_decode_value_cell(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_category_grid_request(
    CategoryGridRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_status_criterion(
    StatusCriterion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_category_cell(CategoryCell self, SseSerializer serializer);

  @protected
  void sse_encode_category_grid(CategoryGrid self, SseSerializer serializer);

  @protected
  void sse_encode_category_grid_request(
    CategoryGridRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_category_match(CategoryMatch self, SseSerializer serializer);

  @protected
  void sse_encode_column_entry(ColumnEntry self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_category_cell(
    List<CategoryCell> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_category_match(
    List<CategoryMatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_column_entry(
    List<ColumnEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_column_entry(
    List<List<ColumnEntry>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_opt_box_autoadd_i_32(
    List<int?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_range_category(
    List<RangeCategory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_status_criterion(
    List<StatusCriterion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_status_match(
    List<StatusMatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_table_row(List<TableRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_value_cell(
    List<ValueCell> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_range_category(RangeCategory self, SseSerializer serializer);

  @protected
  void sse_encode_status_criterion(
    StatusCriterion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_status_match(StatusMatch self, SseSerializer serializer);

  @protected
  void sse_encode_table_row(TableRow self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_value_cell(ValueCell self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
