// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_solo_or_pair_effects`, `attribute_resistance_totals`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Calculates elemental resistance for a body-color selection.
List<AttributeResistance> calculateAttributeResistance({
  required BodyColorSelection selection,
  required ResistanceMasterData masterData,
}) => RustLib.instance.api.crateResistanceCalculateAttributeResistance(
  selection: selection,
  masterData: masterData,
);

/// Calculates abnormality resistance for a body-color selection.
List<AbnormalityResistance> calculateColorAbnormalityResistance({
  required BodyColorSelection selection,
  required ResistanceMasterData masterData,
}) => RustLib.instance.api.crateResistanceCalculateColorAbnormalityResistance(
  selection: selection,
  masterData: masterData,
);

/// Combines body-color and head-shape resistance bonuses.
DenpaMenResistances calculateDenpaMenResistances({
  required BodyColorSelection selection,
  required HeadShapeResistanceBonuses headShape,
  required ResistanceMasterData masterData,
}) => RustLib.instance.api.crateResistanceCalculateDenpaMenResistances(
  selection: selection,
  headShape: headShape,
  masterData: masterData,
);

/// Sums growth-stat bonuses from corrections and an additional correction.
StatBonus calculateCorrectionStatBonus({
  required ResistanceCorrectionInput input,
}) => RustLib.instance.api.crateResistanceCalculateCorrectionStatBonus(
  input: input,
);

/// Finds the first body-color selection that produces the requested resistance.
BodyColorSelection? findColorCombination({
  required List<AttributeResistance> target,
  required ResistanceMasterData masterData,
}) => RustLib.instance.api.crateResistanceFindColorCombination(
  target: target,
  masterData: masterData,
);

class AbnormalityResistance {
  final String abnormalityId;
  final int value;

  const AbnormalityResistance({
    required this.abnormalityId,
    required this.value,
  });

  @override
  int get hashCode => abnormalityId.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AbnormalityResistance &&
          runtimeType == other.runtimeType &&
          abnormalityId == other.abnormalityId &&
          value == other.value;
}

class AttributeResistance {
  final String attributeId;
  final int value;

  const AttributeResistance({required this.attributeId, required this.value});

  @override
  int get hashCode => attributeId.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttributeResistance &&
          runtimeType == other.runtimeType &&
          attributeId == other.attributeId &&
          value == other.value;
}

class AttributeResistanceBonus {
  final String attributeId;
  final int bonus;

  const AttributeResistanceBonus({
    required this.attributeId,
    required this.bonus,
  });

  @override
  int get hashCode => attributeId.hashCode ^ bonus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttributeResistanceBonus &&
          runtimeType == other.runtimeType &&
          attributeId == other.attributeId &&
          bonus == other.bonus;
}

class BodyColorAbnormalityResistanceRule {
  final String colorId;
  final List<ResistanceBonus> abnormalityResistanceBonuses;

  const BodyColorAbnormalityResistanceRule({
    required this.colorId,
    required this.abnormalityResistanceBonuses,
  });

  @override
  int get hashCode => colorId.hashCode ^ abnormalityResistanceBonuses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BodyColorAbnormalityResistanceRule &&
          runtimeType == other.runtimeType &&
          colorId == other.colorId &&
          abnormalityResistanceBonuses == other.abnormalityResistanceBonuses;
}

class BodyColorResistanceRule {
  final String colorId;
  final List<AttributeResistanceBonus> attributeResistanceBonuses;

  const BodyColorResistanceRule({
    required this.colorId,
    required this.attributeResistanceBonuses,
  });

  @override
  int get hashCode => colorId.hashCode ^ attributeResistanceBonuses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BodyColorResistanceRule &&
          runtimeType == other.runtimeType &&
          colorId == other.colorId &&
          attributeResistanceBonuses == other.attributeResistanceBonuses;
}

class BodyColorSelection {
  final List<String> bodyColors;
  final bool isSpColor;

  const BodyColorSelection({required this.bodyColors, required this.isSpColor});

  @override
  int get hashCode => bodyColors.hashCode ^ isSpColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BodyColorSelection &&
          runtimeType == other.runtimeType &&
          bodyColors == other.bodyColors &&
          isSpColor == other.isSpColor;
}

class CorrectionBonuses {
  final StatBonus statBonus;
  final List<ResistanceBonus> abnormalityResistanceBonuses;
  final List<AttributeResistanceBonus> attributeResistanceBonuses;

  const CorrectionBonuses({
    required this.statBonus,
    required this.abnormalityResistanceBonuses,
    required this.attributeResistanceBonuses,
  });

  @override
  int get hashCode =>
      statBonus.hashCode ^
      abnormalityResistanceBonuses.hashCode ^
      attributeResistanceBonuses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CorrectionBonuses &&
          runtimeType == other.runtimeType &&
          statBonus == other.statBonus &&
          abnormalityResistanceBonuses == other.abnormalityResistanceBonuses &&
          attributeResistanceBonuses == other.attributeResistanceBonuses;
}

class DenpaMenResistances {
  final List<AbnormalityResistance> abnormalityResistances;
  final List<AttributeResistance> attributeResistance;

  const DenpaMenResistances({
    required this.abnormalityResistances,
    required this.attributeResistance,
  });

  @override
  int get hashCode =>
      abnormalityResistances.hashCode ^ attributeResistance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DenpaMenResistances &&
          runtimeType == other.runtimeType &&
          abnormalityResistances == other.abnormalityResistances &&
          attributeResistance == other.attributeResistance;
}

class HeadShapeResistanceBonuses {
  final List<ResistanceBonus> abnormalityResistanceBonuses;
  final List<AttributeResistanceBonus> attributeResistanceBonuses;

  const HeadShapeResistanceBonuses({
    required this.abnormalityResistanceBonuses,
    required this.attributeResistanceBonuses,
  });

  @override
  int get hashCode =>
      abnormalityResistanceBonuses.hashCode ^
      attributeResistanceBonuses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeadShapeResistanceBonuses &&
          runtimeType == other.runtimeType &&
          abnormalityResistanceBonuses == other.abnormalityResistanceBonuses &&
          attributeResistanceBonuses == other.attributeResistanceBonuses;
}

class ResistanceAttribute {
  final String id;
  final int index;
  final bool isElemental;

  const ResistanceAttribute({
    required this.id,
    required this.index,
    required this.isElemental,
  });

  @override
  int get hashCode => id.hashCode ^ index.hashCode ^ isElemental.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResistanceAttribute &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          index == other.index &&
          isElemental == other.isElemental;
}

class ResistanceBonus {
  final String id;
  final int bonus;

  const ResistanceBonus({required this.id, required this.bonus});

  @override
  int get hashCode => id.hashCode ^ bonus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResistanceBonus &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bonus == other.bonus;
}

class ResistanceCorrectionInput {
  final List<CorrectionBonuses> corrections;
  final CorrectionBonuses additionalCorrection;

  const ResistanceCorrectionInput({
    required this.corrections,
    required this.additionalCorrection,
  });

  @override
  int get hashCode => corrections.hashCode ^ additionalCorrection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResistanceCorrectionInput &&
          runtimeType == other.runtimeType &&
          corrections == other.corrections &&
          additionalCorrection == other.additionalCorrection;
}

class ResistanceMasterData {
  final List<ResistanceAttribute> attributes;
  final List<BodyColorResistanceRule> bodyColorResistanceRules;
  final List<BodyColorAbnormalityResistanceRule>
  bodyColorAbnormalityResistanceRules;

  const ResistanceMasterData({
    required this.attributes,
    required this.bodyColorResistanceRules,
    required this.bodyColorAbnormalityResistanceRules,
  });

  @override
  int get hashCode =>
      attributes.hashCode ^
      bodyColorResistanceRules.hashCode ^
      bodyColorAbnormalityResistanceRules.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResistanceMasterData &&
          runtimeType == other.runtimeType &&
          attributes == other.attributes &&
          bodyColorResistanceRules == other.bodyColorResistanceRules &&
          bodyColorAbnormalityResistanceRules ==
              other.bodyColorAbnormalityResistanceRules;
}

class StatBonus {
  final int hp;
  final int ap;
  final int attack;
  final int defense;
  final int speed;
  final int evasionRate;

  const StatBonus({
    required this.hp,
    required this.ap,
    required this.attack,
    required this.defense,
    required this.speed,
    required this.evasionRate,
  });

  @override
  int get hashCode =>
      hp.hashCode ^
      ap.hashCode ^
      attack.hashCode ^
      defense.hashCode ^
      speed.hashCode ^
      evasionRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatBonus &&
          runtimeType == other.runtimeType &&
          hp == other.hp &&
          ap == other.ap &&
          attack == other.attack &&
          defense == other.defense &&
          speed == other.speed &&
          evasionRate == other.evasionRate;
}
