// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'table_row.dart';

// These functions are ignored because they are not marked as `pub`: `group_by`, `owned`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// For each group shared by `primary` and every criterion in `others`,
/// finds every column where `primary` holds `primary.target_value` and
/// each of `others` holds its own `target_value` at that same column.
/// The reported `line_offset` is whichever `primary` row actually held
/// the matching value.
List<StatusMatch> findMatchingColumns({
  required StatusCriterion primary,
  required List<StatusCriterion> others,
}) => RustLib.instance.api.crateStatusMatchFindMatchingColumns(
  primary: primary,
  others: others,
);

/// One status condition: search `rows` for `target_value`.
class StatusCriterion {
  final List<TableRow> rows;
  final int targetValue;

  const StatusCriterion({required this.rows, required this.targetValue});

  @override
  int get hashCode => rows.hashCode ^ targetValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatusCriterion &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          targetValue == other.targetValue;
}

/// A column that satisfied every given criterion at once.
class StatusMatch {
  final List<String> group;
  final int lineOffset;
  final int columnIndex;

  const StatusMatch({
    required this.group,
    required this.lineOffset,
    required this.columnIndex,
  });

  @override
  int get hashCode =>
      group.hashCode ^ lineOffset.hashCode ^ columnIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatusMatch &&
          runtimeType == other.runtimeType &&
          group == other.group &&
          lineOffset == other.lineOffset &&
          columnIndex == other.columnIndex;
}
