// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Collects every row into one per-column list of non-null entries,
/// keeping every value rather than overwriting on overlap (rows are
/// visited in `line_offset` order for deterministic column ordering).
List<List<ColumnEntry>> collectColumns({required List<TableRow> rows}) =>
    RustLib.instance.api.crateTableRowCollectColumns(rows: rows);

/// One column's non-null value, plus which row it came from.
class ColumnEntry {
  final int value;
  final int lineOffset;

  const ColumnEntry({required this.value, required this.lineOffset});

  @override
  int get hashCode => value.hashCode ^ lineOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColumnEntry &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          lineOffset == other.lineOffset;
}

/// One row of a generic grouped table. `group` is an opaque grouping key
/// (this crate never inspects its meaning); `values` cells are `None`
/// for blank.
class TableRow {
  final List<String> group;
  final int lineOffset;
  final List<int?> values;

  const TableRow({
    required this.group,
    required this.lineOffset,
    required this.values,
  });

  @override
  int get hashCode => group.hashCode ^ lineOffset.hashCode ^ values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableRow &&
          runtimeType == other.runtimeType &&
          group == other.group &&
          lineOffset == other.lineOffset &&
          values == other.values;
}
