name: dm_file
description: A new Flutter package.
version: 0.1.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.10.1

dependencies:
  data_pack:
    path: ../DataPack
  step_dialog:
    path: ../StepDialog
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  path: ^1.9.1
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  freezed: ^3.2.5

flutter:
