[package]
name = "denpamemo_logics"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
indexmap = "2"
wasm-bindgen = { version = "0.2", optional = true }
serde-wasm-bindgen = { version = "0.6", optional = true }
flutter_rust_bridge = "=2.13.0"

[features]
wasm = ["dep:wasm-bindgen", "dep:serde-wasm-bindgen"]
