// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/denpa_men/denpa_men_entity.dart';
import 'data/qr_code/qr_code_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1562260616338364164),
    name: 'DenpaMenEntity',
    lastPropertyId: const obx_int.IdUid(39, 3473083904217281237),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4518677638759927784),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1678332826215474320),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7384834193292633991),
        name: 'bodyColors',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 240743922568522855),
        name: 'isSpColor',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3412817286492428836),
        name: 'headShapeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1529654537423370336),
        name: 'physiqueId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1921853114358389931),
        name: 'personalityId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2324596901086733694),
        name: 'patternId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 150511633125376551),
        name: 'anntenaId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7425614304559427245),
        name: 'happiness',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6770545541219690562),
        name: 'maxHappiness',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1608238419420294109),
        name: 'level',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 428813470595810936),
        name: 'maxLevel',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 502716158300729293),
        name: 'currentExp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 3614088515149994097),
        name: 'maxExp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 3462830622638241361),
        name: 'hp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 5826268725323252208),
        name: 'ap',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 369635564058708228),
        name: 'attack',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 2935931659019258784),
        name: 'defense',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 161778045795335911),
        name: 'speed',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 7118546690303302775),
        name: 'evasionRate',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 1918332064718651983),
        name: 'correctionIds',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 8338000133373889233),
        name: 'memo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 4509287055483744944),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 2384250894206438545),
        name: 'moveInDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 4119833927849556695),
        name: 'qrCodeId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 4149304241743661584),
        relationField: 'qrCode',
        relationTarget: 'QrCodeEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 7474464096521119322),
        name: 'cuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 6232781287230050291),
        name: 'parentIds',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 275029249087611936),
        name: 'catchOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 5701588058507270646),
        name: 'considerCorrections',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 2946344687157787876),
        name: 'antennaLevel',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 4619165505260223847),
        name: 'bodyColorShades',
        type: 27,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 5724398760579049796),
        name: 'hash',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 584456325217302226),
        name: 'monsterExpMonsterId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(35, 7898687205623347596),
        name: 'monsterExpCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 6324361579409960967),
        name: 'monsterExpValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(37, 3234012520861903854),
        name: 'monsterExpLevel',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(38, 2134945977364214541),
        name: 'monsterExpMaxLevelTeammateCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(39, 3473083904217281237),
        name: 'monsterExpRecipientCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7586720445347852204),
    name: 'QrCodeEntity',
    lastPropertyId: const obx_int.IdUid(6, 9075432342033460347),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8136527907161312430),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5051089340257853467),
        name: 'rawValue',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7865551652871338519),
        name: 'hash',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 2492110792462433612),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5963905535047034243),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4503194552387054123),
        name: 'cuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9075432342033460347),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 7586720445347852204),
    lastIndexId: const obx_int.IdUid(2, 2492110792462433612),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DenpaMenEntity: obx_int.EntityDefinition<DenpaMenEntity>(
      model: _entities[0],
      toOneRelations: (DenpaMenEntity object) => [object.qrCode],
      toManyRelations: (DenpaMenEntity object) => {},
      getId: (DenpaMenEntity object) => object.id,
      setId: (DenpaMenEntity object, int id) {
        object.id = id;
      },
      objectToFB: (DenpaMenEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final bodyColorsOffset = fbb.writeList(
          object.bodyColors.map(fbb.writeString).toList(growable: false),
        );
        final headShapeIdOffset = fbb.writeString(object.headShapeId);
        final physiqueIdOffset = fbb.writeString(object.physiqueId);
        final personalityIdOffset = fbb.writeString(object.personalityId);
        final patternIdOffset = fbb.writeString(object.patternId);
        final anntenaIdOffset = fbb.writeString(object.anntenaId);
        final correctionIdsOffset = fbb.writeList(
          object.correctionIds.map(fbb.writeString).toList(growable: false),
        );
        final memoOffset = object.memo == null
            ? null
            : fbb.writeString(object.memo!);
        final cuidOffset = fbb.writeString(object.cuid);
        final parentIdsOffset = fbb.writeList(
          object.parentIds.map(fbb.writeString).toList(growable: false),
        );
        final bodyColorShadesOffset = fbb.writeListInt64(
          object.bodyColorShades,
        );
        final hashOffset = fbb.writeString(object.hash);
        final monsterExpMonsterIdOffset = object.monsterExpMonsterId == null
            ? null
            : fbb.writeString(object.monsterExpMonsterId!);
        fbb.startTable(40);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, bodyColorsOffset);
        fbb.addBool(3, object.isSpColor);
        fbb.addOffset(4, headShapeIdOffset);
        fbb.addOffset(5, physiqueIdOffset);
        fbb.addOffset(6, personalityIdOffset);
        fbb.addOffset(7, patternIdOffset);
        fbb.addOffset(8, anntenaIdOffset);
        fbb.addInt64(9, object.happiness);
        fbb.addInt64(10, object.maxHappiness);
        fbb.addInt64(11, object.level);
        fbb.addInt64(12, object.maxLevel);
        fbb.addInt64(13, object.currentExp);
        fbb.addInt64(14, object.maxExp);
        fbb.addInt64(15, object.hp);
        fbb.addInt64(16, object.ap);
        fbb.addInt64(17, object.attack);
        fbb.addInt64(18, object.defense);
        fbb.addInt64(19, object.speed);
        fbb.addInt64(20, object.evasionRate);
        fbb.addOffset(21, correctionIdsOffset);
        fbb.addOffset(22, memoOffset);
        fbb.addInt64(23, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(24, object.moveInDate?.millisecondsSinceEpoch);
        fbb.addInt64(25, object.qrCode.targetId);
        fbb.addOffset(26, cuidOffset);
        fbb.addOffset(27, parentIdsOffset);
        fbb.addInt64(28, object.catchOrder);
        fbb.addBool(29, object.considerCorrections);
        fbb.addInt64(30, object.antennaLevel);
        fbb.addOffset(31, bodyColorShadesOffset);
        fbb.addOffset(32, hashOffset);
        fbb.addOffset(33, monsterExpMonsterIdOffset);
        fbb.addInt64(34, object.monsterExpCount);
        fbb.addInt64(35, object.monsterExpValue);
        fbb.addInt64(36, object.monsterExpLevel);
        fbb.addInt64(37, object.monsterExpMaxLevelTeammateCount);
        fbb.addInt64(38, object.monsterExpRecipientCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final moveInDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          52,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final cuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 56, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final bodyColorsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final bodyColorShadesParam = const fb.ListReader<int>(
          fb.Int64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 66, []);
        final parentIdsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 58, []);
        final isSpColorParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final headShapeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final physiqueIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final personalityIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final patternIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final anntenaIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final antennaLevelParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          64,
          0,
        );
        final happinessParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final maxHappinessParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final levelParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final maxLevelParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final currentExpParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final maxExpParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final hpParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        final apParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final attackParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        final defenseParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          40,
          0,
        );
        final speedParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          42,
          0,
        );
        final evasionRateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          44,
          0,
        );
        final correctionIdsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 46, []);
        final considerCorrectionsParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          62,
          false,
        );
        final catchOrderParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          60,
        );
        final memoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final hashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 68, '');
        final monsterExpMonsterIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 70);
        final monsterExpCountParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          72,
        );
        final monsterExpValueParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          74,
        );
        final monsterExpLevelParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          76,
        );
        final monsterExpMaxLevelTeammateCountParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 78);
        final monsterExpRecipientCountParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 80);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 50, 0),
        );
        final moveInDateParam = moveInDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(moveInDateValue);
        final object = DenpaMenEntity(
          id: idParam,
          cuid: cuidParam,
          name: nameParam,
          bodyColors: bodyColorsParam,
          bodyColorShades: bodyColorShadesParam,
          parentIds: parentIdsParam,
          isSpColor: isSpColorParam,
          headShapeId: headShapeIdParam,
          physiqueId: physiqueIdParam,
          personalityId: personalityIdParam,
          patternId: patternIdParam,
          anntenaId: anntenaIdParam,
          antennaLevel: antennaLevelParam,
          happiness: happinessParam,
          maxHappiness: maxHappinessParam,
          level: levelParam,
          maxLevel: maxLevelParam,
          currentExp: currentExpParam,
          maxExp: maxExpParam,
          hp: hpParam,
          ap: apParam,
          attack: attackParam,
          defense: defenseParam,
          speed: speedParam,
          evasionRate: evasionRateParam,
          correctionIds: correctionIdsParam,
          considerCorrections: considerCorrectionsParam,
          catchOrder: catchOrderParam,
          memo: memoParam,
          hash: hashParam,
          monsterExpMonsterId: monsterExpMonsterIdParam,
          monsterExpCount: monsterExpCountParam,
          monsterExpValue: monsterExpValueParam,
          monsterExpLevel: monsterExpLevelParam,
          monsterExpMaxLevelTeammateCount: monsterExpMaxLevelTeammateCountParam,
          monsterExpRecipientCount: monsterExpRecipientCountParam,
          createdAt: createdAtParam,
          moveInDate: moveInDateParam,
        );
        object.qrCode.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          54,
          0,
        );
        object.qrCode.attach(store);
        return object;
      },
    ),
    QrCodeEntity: obx_int.EntityDefinition<QrCodeEntity>(
      model: _entities[1],
      toOneRelations: (QrCodeEntity object) => [],
      toManyRelations: (QrCodeEntity object) => {},
      getId: (QrCodeEntity object) => object.id,
      setId: (QrCodeEntity object, int id) {
        object.id = id;
      },
      objectToFB: (QrCodeEntity object, fb.Builder fbb) {
        final rawValueOffset = fbb.writeString(object.rawValue);
        final hashOffset = fbb.writeString(object.hash);
        final cuidOffset = fbb.writeString(object.cuid);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, rawValueOffset);
        fbb.addOffset(2, hashOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(4, cuidOffset);
        fbb.addOffset(5, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final cuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final rawValueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final hashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = QrCodeEntity(
          id: idParam,
          cuid: cuidParam,
          rawValue: rawValueParam,
          hash: hashParam,
          createdAt: createdAtParam,
          name: nameParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DenpaMenEntity] entity fields to define ObjectBox queries.
class DenpaMenEntity_ {
  /// See [DenpaMenEntity.id].
  static final id = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[0],
  );

  /// See [DenpaMenEntity.name].
  static final name = obx.QueryStringProperty<DenpaMenEntity>(
    _entities[0].properties[1],
  );

  /// See [DenpaMenEntity.bodyColors].
  static final bodyColors = obx.QueryStringVectorProperty<DenpaMenEntity>(
    _entities[0].properties[2],
  );

  /// See [DenpaMenEntity.isSpColor].
  static final isSpColor = obx.QueryBooleanProperty<DenpaMenEntity>(
    _entities[0].properties[3],
  );

  /// See [DenpaMenEntity.headShapeId].
  static final headShapeId = obx.QueryStringProperty<DenpaMenEntity>(
    _entities[0].properties[4],
  );

  /// See [DenpaMenEntity.physiqueId].
  static final physiqueId = obx.QueryStringProperty<DenpaMenEntity>(
    _entities[0].properties[5],
  );

  /// See [DenpaMenEntity.personalityId].
  static final personalityId = obx.QueryStringProperty<DenpaMenEntity>(
    _entities[0].properties[6],
  );

  /// See [DenpaMenEntity.patternId].
  static final patternId = obx.QueryStringProperty<DenpaMenEntity>(
    _entities[0].properties[7],
  );

  /// See [DenpaMenEntity.anntenaId].
  static final anntenaId = obx.QueryStringProperty<DenpaMenEntity>(
    _entities[0].properties[8],
  );

  /// See [DenpaMenEntity.happiness].
  static final happiness = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[9],
  );

  /// See [DenpaMenEntity.maxHappiness].
  static final maxHappiness = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[10],
  );

  /// See [DenpaMenEntity.level].
  static final level = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[11],
  );

  /// See [DenpaMenEntity.maxLevel].
  static final maxLevel = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[12],
  );

  /// See [DenpaMenEntity.currentExp].
  static final currentExp = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[13],
  );

  /// See [DenpaMenEntity.maxExp].
  static final maxExp = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[14],
  );

  /// See [DenpaMenEntity.hp].
  static final hp = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[15],
  );

  /// See [DenpaMenEntity.ap].
  static final ap = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[16],
  );

  /// See [DenpaMenEntity.attack].
  static final attack = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[17],
  );

  /// See [DenpaMenEntity.defense].
  static final defense = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[18],
  );

  /// See [DenpaMenEntity.speed].
  static final speed = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[19],
  );

  /// See [DenpaMenEntity.evasionRate].
  static final evasionRate = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[20],
  );

  /// See [DenpaMenEntity.correctionIds].
  static final correctionIds = obx.QueryStringVectorProperty<DenpaMenEntity>(
    _entities[0].properties[21],
  );

  /// See [DenpaMenEntity.memo].
  static final memo = obx.QueryStringProperty<DenpaMenEntity>(
    _entities[0].properties[22],
  );

  /// See [DenpaMenEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<DenpaMenEntity>(
    _entities[0].properties[23],
  );

  /// See [DenpaMenEntity.moveInDate].
  static final moveInDate = obx.QueryDateProperty<DenpaMenEntity>(
    _entities[0].properties[24],
  );

  /// See [DenpaMenEntity.qrCode].
  static final qrCode = obx.QueryRelationToOne<DenpaMenEntity, QrCodeEntity>(
    _entities[0].properties[25],
  );

  /// See [DenpaMenEntity.cuid].
  static final cuid = obx.QueryStringProperty<DenpaMenEntity>(
    _entities[0].properties[26],
  );

  /// See [DenpaMenEntity.parentIds].
  static final parentIds = obx.QueryStringVectorProperty<DenpaMenEntity>(
    _entities[0].properties[27],
  );

  /// See [DenpaMenEntity.catchOrder].
  static final catchOrder = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[28],
  );

  /// See [DenpaMenEntity.considerCorrections].
  static final considerCorrections = obx.QueryBooleanProperty<DenpaMenEntity>(
    _entities[0].properties[29],
  );

  /// See [DenpaMenEntity.antennaLevel].
  static final antennaLevel = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[30],
  );

  /// See [DenpaMenEntity.bodyColorShades].
  static final bodyColorShades = obx.QueryIntegerVectorProperty<DenpaMenEntity>(
    _entities[0].properties[31],
  );

  /// See [DenpaMenEntity.hash].
  static final hash = obx.QueryStringProperty<DenpaMenEntity>(
    _entities[0].properties[32],
  );

  /// See [DenpaMenEntity.monsterExpMonsterId].
  static final monsterExpMonsterId = obx.QueryStringProperty<DenpaMenEntity>(
    _entities[0].properties[33],
  );

  /// See [DenpaMenEntity.monsterExpCount].
  static final monsterExpCount = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[34],
  );

  /// See [DenpaMenEntity.monsterExpValue].
  static final monsterExpValue = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[35],
  );

  /// See [DenpaMenEntity.monsterExpLevel].
  static final monsterExpLevel = obx.QueryIntegerProperty<DenpaMenEntity>(
    _entities[0].properties[36],
  );

  /// See [DenpaMenEntity.monsterExpMaxLevelTeammateCount].
  static final monsterExpMaxLevelTeammateCount =
      obx.QueryIntegerProperty<DenpaMenEntity>(_entities[0].properties[37]);

  /// See [DenpaMenEntity.monsterExpRecipientCount].
  static final monsterExpRecipientCount =
      obx.QueryIntegerProperty<DenpaMenEntity>(_entities[0].properties[38]);
}

/// [QrCodeEntity] entity fields to define ObjectBox queries.
class QrCodeEntity_ {
  /// See [QrCodeEntity.id].
  static final id = obx.QueryIntegerProperty<QrCodeEntity>(
    _entities[1].properties[0],
  );

  /// See [QrCodeEntity.rawValue].
  static final rawValue = obx.QueryStringProperty<QrCodeEntity>(
    _entities[1].properties[1],
  );

  /// See [QrCodeEntity.hash].
  static final hash = obx.QueryStringProperty<QrCodeEntity>(
    _entities[1].properties[2],
  );

  /// See [QrCodeEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<QrCodeEntity>(
    _entities[1].properties[3],
  );

  /// See [QrCodeEntity.cuid].
  static final cuid = obx.QueryStringProperty<QrCodeEntity>(
    _entities[1].properties[4],
  );

  /// See [QrCodeEntity.name].
  static final name = obx.QueryStringProperty<QrCodeEntity>(
    _entities[1].properties[5],
  );
}
