name = "denpa-memo-auth"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[dev]
port = 8787

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "denpa-memo-storage"
preview_bucket_name = "denpa-memo-storage-dev"

[env.production]
name = "denpa-memo-auth"

[env.production.vars]
FIREBASE_PROJECT_ID = "denpa-memo-29dda"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "denpa-memo-storage"

[env.development]
name = "denpa-memo-auth-dev"

[env.development.vars]
FIREBASE_PROJECT_ID = "denpa-memo-dev"

[[env.development.r2_buckets]]
binding = "STORAGE"
bucket_name = "denpa-memo-storage-dev"
